#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: AccoladesRuntime

#include "Basic.hpp"

#include "FortniteGame_structs.hpp"
#include "FortniteGame_classes.hpp"
#include "AccoladesRuntime_structs.hpp"
#include "CoreUObject_classes.hpp"
#include "GameFeatures_classes.hpp"


namespace SDK
{

// Class AccoladesRuntime.PFWAccoladeCollection_Container
// 0x0020 (0x0160 - 0x0140)
class UPFWAccoladeCollection_Container final : public UPersistenceFrameworkContainer
{
public:
	uint8                                         Pad_140[0x20];                                     // 0x0140(0x0020)(Fixing Struct Size After Last Property [ Dumper-8 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PFWAccoladeCollection_Container">();
	}
	static class UPFWAccoladeCollection_Container* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPFWAccoladeCollection_Container>();
	}
};

// Class AccoladesRuntime.PFWAccoladeCollection_Module
// 0x0000 (0x00E0 - 0x00E0)
class UPFWAccoladeCollection_Module final : public UPersistenceFrameworkModule
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PFWAccoladeCollection_Module">();
	}
	static class UPFWAccoladeCollection_Module* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPFWAccoladeCollection_Module>();
	}
};

// Class AccoladesRuntime.PFWAccoladeCollection_Trigger
// 0x0000 (0x00C0 - 0x00C0)
class UPFWAccoladeCollection_Trigger final : public UPersistenceFrameworkSaveTrigger_Manual
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PFWAccoladeCollection_Trigger">();
	}
	static class UPFWAccoladeCollection_Trigger* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPFWAccoladeCollection_Trigger>();
	}
};

// Class AccoladesRuntime.PFWAccoladeCollection_FilteredListContainer
// 0x0010 (0x0160 - 0x0150)
class UPFWAccoladeCollection_FilteredListContainer final : public UPersistenceFrameworkFilteredListContainer
{
public:
	uint8                                         Pad_150[0x10];                                     // 0x0150(0x0010)(Fixing Struct Size After Last Property [ Dumper-8 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PFWAccoladeCollection_FilteredListContainer">();
	}
	static class UPFWAccoladeCollection_FilteredListContainer* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPFWAccoladeCollection_FilteredListContainer>();
	}
};

// Class AccoladesRuntime.FortAccoladeCollectionFeatureCollector
// 0x0010 (0x0038 - 0x0028)
class UFortAccoladeCollectionFeatureCollector final : public UObject
{
public:
	uint8                                         Pad_28[0x10];                                      // 0x0028(0x0010)(Fixing Struct Size After Last Property [ Dumper-8 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"FortAccoladeCollectionFeatureCollector">();
	}
	static class UFortAccoladeCollectionFeatureCollector* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFortAccoladeCollectionFeatureCollector>();
	}
};

// Class AccoladesRuntime.GameFeatureAction_AddAccoladeTable
// 0x0020 (0x0048 - 0x0028)
class UGameFeatureAction_AddAccoladeTable final : public UGameFeatureAction
{
public:
	TSoftObjectPtr<class UDataTable>              AccoladeTable;                                     // 0x0028(0x0020)(Edit, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"GameFeatureAction_AddAccoladeTable">();
	}
	static class UGameFeatureAction_AddAccoladeTable* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGameFeatureAction_AddAccoladeTable>();
	}
};

// Class AccoladesRuntime.FortCheatManager_Accolades
// 0x0000 (0x0028 - 0x0028)
class UFortCheatManager_Accolades final : public UChildCheatManager
{
public:
	void ResetAccoladeData();
	void TriggerAccolade(const class FString& AccoladeName);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"FortCheatManager_Accolades">();
	}
	static class UFortCheatManager_Accolades* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFortCheatManager_Accolades>();
	}
};

// Class AccoladesRuntime.FortControllerComponent_AccoladeCollection
// 0x0278 (0x0320 - 0x00A8)
class UFortControllerComponent_AccoladeCollection final : public UFortControllerComponent
{
public:
	uint8                                         Pad_A8[0xD0];                                      // 0x00A8(0x00D0)(Fixing Size After Last Property [ Dumper-8 ])
	class FName                                   PinnedAccoladeName;                                // 0x0178(0x0004)(Net, ZeroConstructor, Transient, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_17C[0x74];                                     // 0x017C(0x0074)(Fixing Size After Last Property [ Dumper-8 ])
	struct FPersistenceFrameworkSaveControl       SaveControl;                                       // 0x01F0(0x0010)(NoDestructor, NativeAccessSpecifierPrivate)
	struct FFortAccoladeCollectionDataArray       AccoladeCollectionDataArray;                       // 0x0200(0x0120)(Net, Transient, NativeAccessSpecifierPrivate)

public:
	void ClientNotifyRestored(const EPersistenceFrameworkResult Result);
	void ClientResetAccoladeData();
	void HandlePinnedQuestChanged(const struct FAthenaPinnedQuestData& PinnedQuestData);
	void HandlePlayerProfileInitialized();
	void OnEndMatchForPlayer(class UFortControllerComponent_EndMatchPersistence* EndMatchPersistence);
	void OnRep_PinnedAccoladeName(class FName OldPinnedAccoladeName);
	void ServerMarkAccoladesAsSeen(const TArray<class FName>& AccoladeNames);
	void ServerPinAccolade(const class FName AccoladeName);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"FortControllerComponent_AccoladeCollection">();
	}
	static class UFortControllerComponent_AccoladeCollection* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFortControllerComponent_AccoladeCollection>();
	}
};

// Class AccoladesRuntime.FortControllerComponent_Accolades
// 0x0478 (0x0520 - 0x00A8)
class UFortControllerComponent_Accolades final : public UFortControllerComponent
{
public:
	uint8                                         Pad_A8[0x1E8];                                     // 0x00A8(0x01E8)(Fixing Size After Last Property [ Dumper-8 ])
	struct FFortUpdatedTrackedAccoladeDataArray   UpdatedTrackedAccoladeDataArray;                   // 0x0290(0x0120)(Net, Transient, NativeAccessSpecifierPrivate)
	struct FFortCompletedAccoladeDataArray        CompletedAccoladeDataArray;                        // 0x03B0(0x0120)(Net, Transient, NativeAccessSpecifierPrivate)
	uint8                                         Pad_4D0[0x50];                                     // 0x04D0(0x0050)(Fixing Struct Size After Last Property [ Dumper-8 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"FortControllerComponent_Accolades">();
	}
	static class UFortControllerComponent_Accolades* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFortControllerComponent_Accolades>();
	}
};

// Class AccoladesRuntime.FortGameStateComponent_AccoladeCollection
// 0x0010 (0x00B0 - 0x00A0)
class UFortGameStateComponent_AccoladeCollection final : public UFortGameStateComponent
{
public:
	uint8                                         Pad_A0[0x10];                                      // 0x00A0(0x0010)(Fixing Struct Size After Last Property [ Dumper-8 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"FortGameStateComponent_AccoladeCollection">();
	}
	static class UFortGameStateComponent_AccoladeCollection* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFortGameStateComponent_AccoladeCollection>();
	}
};

// Class AccoladesRuntime.FortGameStateComponent_Accolades
// 0x00F8 (0x0198 - 0x00A0)
class UFortGameStateComponent_Accolades final : public UFortGameStateComponent
{
public:
	uint8                                         Pad_A0[0xF8];                                      // 0x00A0(0x00F8)(Fixing Struct Size After Last Property [ Dumper-8 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"FortGameStateComponent_Accolades">();
	}
	static class UFortGameStateComponent_Accolades* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFortGameStateComponent_Accolades>();
	}
};

}

