#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: AudioGameplay

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"
#include "GameplayTags_structs.hpp"
#include "Engine_classes.hpp"
#include "AudioExtensions_structs.hpp"


namespace SDK
{

// Class AudioGameplay.AudioAssetUserData
// 0x0020 (0x0048 - 0x0028)
class UAudioAssetUserData final : public UAssetUserData
{
public:
	struct FGameplayTagContainer                  MetadataTags;                                      // 0x0028(0x0020)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"AudioAssetUserData">();
	}
	static class UAudioAssetUserData* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAudioAssetUserData>();
	}
};

// Class AudioGameplay.AudioComponentGroupExtension
// 0x0000 (0x0000 - 0x0000)
class IAudioComponentGroupExtension final
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"AudioComponentGroupExtension">();
	}
	static class IAudioComponentGroupExtension* GetDefaultObj()
	{
		return GetDefaultObjImpl<IAudioComponentGroupExtension>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};

// Class AudioGameplay.AudioGameplayCondition
// 0x0000 (0x0000 - 0x0000)
class IAudioGameplayCondition final
{
public:
	bool ConditionMet() const;
	bool ConditionMet_Position(const struct FVector& Position) const;

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"AudioGameplayCondition">();
	}
	static class IAudioGameplayCondition* GetDefaultObj()
	{
		return GetDefaultObjImpl<IAudioGameplayCondition>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};

// Class AudioGameplay.AudioGameplayVolumeInteraction
// 0x0000 (0x0000 - 0x0000)
class IAudioGameplayVolumeInteraction final
{
public:
	void OnListenerEnter();
	void OnListenerExit();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"AudioGameplayVolumeInteraction">();
	}
	static class IAudioGameplayVolumeInteraction* GetDefaultObj()
	{
		return GetDefaultObjImpl<IAudioGameplayVolumeInteraction>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};

// Class AudioGameplay.SoundHandleSubsystem
// 0x00B0 (0x00E0 - 0x0030)
class USoundHandleSubsystem final : public UAudioEngineSubsystem
{
public:
	uint8                                         Pad_30[0xB0];                                      // 0x0030(0x00B0)(Fixing Struct Size After Last Property [ Dumper-8 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"SoundHandleSubsystem">();
	}
	static class USoundHandleSubsystem* GetDefaultObj()
	{
		return GetDefaultObjImpl<USoundHandleSubsystem>();
	}
};

// Class AudioGameplay.AudioComponentGroup
// 0x01B0 (0x03D0 - 0x0220)
#pragma pack(push, 0x1)
class alignas(0x10) UAudioComponentGroup : public USceneComponent
{
public:
	uint8                                         Pad_220[0x8];                                      // 0x0220(0x0008)(Fixing Size After Last Property [ Dumper-8 ])
	TMulticastInlineDelegate<void()>              OnStopped;                                         // 0x0228(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void()>              OnKilled;                                          // 0x0238(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void()>              OnVirtualized;                                     // 0x0248(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void()>              OnUnvirtualized;                                   // 0x0258(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TArray<class UAudioComponent*>                Components;                                        // 0x0268(0x0010)(Edit, ExportObject, ZeroConstructor, EditConst, ContainsInstancedReference, Protected, UObjectWrapper, NativeAccessSpecifierProtected)
	TArray<struct FAudioParameter>                ParamsToSet;                                       // 0x0278(0x0010)(ZeroConstructor, Transient, Protected, NativeAccessSpecifierProtected)
	TArray<struct FAudioParameter>                PersistentParams;                                  // 0x0288(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, EditConst, Protected, NativeAccessSpecifierProtected)
	TArray<TScriptInterface<class IAudioComponentGroupExtension>> Extensions;                        // 0x0298(0x0010)(ZeroConstructor, Transient, Protected, UObjectWrapper, NativeAccessSpecifierProtected)
	uint8                                         Pad_2A8[0x120];                                    // 0x02A8(0x0120)(Fixing Struct Size After Last Property [ Dumper-8 ])

public:
	static class UAudioComponentGroup* StaticGetOrCreateComponentGroup(class AActor* Actor);

	void AddExtension(TScriptInterface<class IAudioComponentGroupExtension> NewExtension);
	void AddExternalComponent(class UAudioComponent* ComponentToAdd);
	void BroadcastEvent(const class FName EventName);
	void BroadcastKill();
	void BroadcastStopAll();
	void DisableVirtualization();
	void EnableVirtualization();
	void RemoveExtension(TScriptInterface<class IAudioComponentGroupExtension> NewExtension);
	void RemoveExternalComponent(class UAudioComponent* ComponentToRemove);
	void SetLowPassFilter(const float InFrequency);
	void SetPitchMultiplier(const float InPitch);
	void SetVolumeMultiplier(const float InVolume);
	void StopSound(class USoundBase* Sound, const float FadeTime);
	void SubscribeToBool(const class FName ParamName, TDelegate<void(const bool ParamValue)> Delegate);
	void SubscribeToEvent(const class FName EventName, TDelegate<void(const class FName& EventName)> Delegate);
	void SubscribeToStringParam(const class FName ParamName, TDelegate<void(const class FString& Value)> Delegate);
	void UnsubscribeObject(const class UObject* Object);

	bool GetBoolParamValue(const class FName ParamName) const;
	float GetFloatParamValue(const class FName ParamName) const;
	class FString GetStringParamValue(const class FName ParamName) const;
	bool IsPlayingAny() const;
	bool IsVirtualized() const;

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"AudioComponentGroup">();
	}
	static class UAudioComponentGroup* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAudioComponentGroup>();
	}
};
#pragma pack(pop)

// Class AudioGameplay.AudioGameplayComponent
// 0x0008 (0x00A8 - 0x00A0)
class UAudioGameplayComponent : public UActorComponent
{
public:
	uint8                                         Pad_A0[0x8];                                       // 0x00A0(0x0008)(Fixing Struct Size After Last Property [ Dumper-8 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"AudioGameplayComponent">();
	}
	static class UAudioGameplayComponent* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAudioGameplayComponent>();
	}
};

// Class AudioGameplay.AudioRequirementPreset
// 0x0048 (0x0078 - 0x0030)
class UAudioRequirementPreset final : public UDataAsset
{
public:
	struct FGameplayTagQuery                      Query;                                             // 0x0030(0x0048)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"AudioRequirementPreset">();
	}
	static class UAudioRequirementPreset* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAudioRequirementPreset>();
	}
};

// Class AudioGameplay.AudioParameterComponent
// 0x0030 (0x00D8 - 0x00A8)
class UAudioParameterComponent : public UAudioGameplayComponent
{
public:
	uint8                                         Pad_A8[0x10];                                      // 0x00A8(0x0010)(Fixing Size After Last Property [ Dumper-8 ])
	TArray<TWeakObjectPtr<class UAudioComponent>> ActiveComponents;                                  // 0x00B8(0x0010)(ExportObject, ZeroConstructor, Transient, ContainsInstancedReference, UObjectWrapper, NativeAccessSpecifierPrivate)
	TArray<struct FAudioParameter>                Parameters;                                        // 0x00C8(0x0010)(Edit, ZeroConstructor, DisableEditOnInstance, NativeAccessSpecifierPrivate)

public:
	const TArray<struct FAudioParameter> GetParameters() const;

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"AudioParameterComponent">();
	}
	static class UAudioParameterComponent* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAudioParameterComponent>();
	}
};

}

