#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: B_Shotgun_Generic

#include "Basic.hpp"

#include "B_Ranged_Generic_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass B_Shotgun_Generic.B_Shotgun_Generic_C
// 0x0000 (0x2130 - 0x2130)
class AB_Shotgun_Generic_C : public AB_Ranged_Generic_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"B_Shotgun_Generic_C">();
	}
	static class AB_Shotgun_Generic_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AB_Shotgun_Generic_C>();
	}
};

}

