#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BP_AssignedObjectiveGameStateComponent

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "GameplayAbilities_structs.hpp"
#include "MidMatchAssignedGameplayRuntime_classes.hpp"
#include "FortniteGame_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_AssignedObjectiveGameStateComponent.BP_AssignedObjectiveGameStateComponent_C
// 0x00F0 (0x02C0 - 0x01D0)
class UBP_AssignedObjectiveGameStateComponent_C final : public UFortGameStateComponent_AssignedObjective
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x01D0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	bool                                          bDebug;                                            // 0x01D8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1D9[0x7];                                      // 0x01D9(0x0007)(Fixing Size After Last Property [ Dumper-8 ])
	struct FScalableFloat                         hf_ObjectiveSpawningEnabled;                       // 0x01E0(0x0028)(Edit, BlueprintVisible, DisableEditOnInstance)
	int32                                         StormCircleCount;                                  // 0x0208(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_20C[0x4];                                      // 0x020C(0x0004)(Fixing Size After Last Property [ Dumper-8 ])
	struct FScalableFloat                         HF_StormPhaseStepToSpawn;                          // 0x0210(0x0028)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FScalableFloat                         HF_StormPhaseCountToSpawn;                         // 0x0238(0x0028)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FScalableFloat                         HF_DelayFromStormPhaseToSpawn;                     // 0x0260(0x0028)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FScalableFloat                         HF_AllowedInMode;                                  // 0x0288(0x0028)(Edit, BlueprintVisible, DisableEditOnInstance)
	class UAsyncAction_StartListeningToStatefulEvent* GamePhaseStepUpdatedAsyncTask;                 // 0x02B0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class UAsyncAction_StartListeningToStatefulEvent* CreativeStormShieldGamePhaseStepUpdatedAsyncTask; // 0x02B8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void ReceiveEndPlay(EEndPlayReason EndPlayReason);
	void ReceiveBeginPlay();
	void OnSavedEventStateExists_CD5BAC1E4DD570BE3AE79193F64FB2D5(class UAsyncAction_StartListeningToStatefulEvent* ProxyObject);
	void OnSavedEventStateExists_7726A0C544CD1DD1FFD035B6210A548C(class UAsyncAction_StartListeningToStatefulEvent* ProxyObject);
	void OnReady_C39E560349384636A84423A916E28622(class AFortGameStateAthena* GameState, const class UFortPlaylist* Playlist, const struct FGameplayTagContainer& PlaylistContextTags);
	void OnGamePhaseStepChanged(const EAthenaGamePhaseStep GamePhaseStep);
	void OnEventStateCleared_CD5BAC1E4DD570BE3AE79193F64FB2D5(class UAsyncAction_StartListeningToStatefulEvent* ProxyObject);
	void OnEventStateCleared_7726A0C544CD1DD1FFD035B6210A548C(class UAsyncAction_StartListeningToStatefulEvent* ProxyObject);
	void OnEventReceived_CD5BAC1E4DD570BE3AE79193F64FB2D5(class UAsyncAction_StartListeningToStatefulEvent* ProxyObject);
	void OnEventReceived_7726A0C544CD1DD1FFD035B6210A548C(class UAsyncAction_StartListeningToStatefulEvent* ProxyObject);
	void OnAssignedObjectiveReady(struct FFortAssignedObjectiveData& ObjectiveData);
	void ExecuteUbergraph_BP_AssignedObjectiveGameStateComponent(int32 EntryPoint);
	void DebugStartAssignedObjectives();
	void DebugDrawSquadAvgLocs();

	const class UObject* GetCacheContextOverride() const;
	bool BuildDataRegistryResolverScope(TArray<class FName>* InOutResolverScopes, int32* InOutPriority) const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_AssignedObjectiveGameStateComponent_C">();
	}
	static class UBP_AssignedObjectiveGameStateComponent_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_AssignedObjectiveGameStateComponent_C>();
	}
};

}

