#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BPI_DynVariantRow_FocusTargetWidget

#include "Basic.hpp"

#include "BPI_DynVariantRow_FocusTargetWidget_classes.hpp"
#include "BPI_DynVariantRow_FocusTargetWidget_parameters.hpp"


namespace SDK
{

// Function BPI_DynVariantRow_FocusTargetWidget.BPI_DynVariantRow_FocusTargetWidget_C.GetDesiredFocusTarget
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class UWidget**                         FocusTarget                                            (Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void IBPI_DynVariantRow_FocusTargetWidget_C::GetDesiredFocusTarget(class UWidget** FocusTarget) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("BPI_DynVariantRow_FocusTargetWidget_C", "GetDesiredFocusTarget");

	Params::BPI_DynVariantRow_FocusTargetWidget_C_GetDesiredFocusTarget Parms{};

	AsUObject()->ProcessEvent(Func, &Parms);

	if (FocusTarget != nullptr)
		*FocusTarget = Parms.FocusTarget;
}

}

