#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BPS30_BattlePassRewardTrack

#include "Basic.hpp"

#include "BPS30_BattlePassRewardTrack_classes.hpp"
#include "BPS30_BattlePassRewardTrack_parameters.hpp"


namespace SDK
{

// Function BPS30_BattlePassRewardTrack.BPS30_BattlePassRewardTrack_C.ExecuteUbergraph_BPS30_BattlePassRewardTrack
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPS30_BattlePassRewardTrack_C::ExecuteUbergraph_BPS30_BattlePassRewardTrack(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPS30_BattlePassRewardTrack_C", "ExecuteUbergraph_BPS30_BattlePassRewardTrack");

	Params::BPS30_BattlePassRewardTrack_C_ExecuteUbergraph_BPS30_BattlePassRewardTrack Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPS30_BattlePassRewardTrack.BPS30_BattlePassRewardTrack_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UBPS30_BattlePassRewardTrack_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPS30_BattlePassRewardTrack_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}

}

