#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: ContextualTraversalRuntime

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "FortniteGame_structs.hpp"


namespace SDK
{

// ScriptStruct ContextualTraversalRuntime.FortMovementMode_TraversalBaseCreationData
// 0x0128 (0x0130 - 0x0008)
#pragma pack(push, 0x1)
struct alignas(0x10) FFortMovementMode_TraversalBaseCreationData : public FFortMovementMode_BaseExtCreationData
{
public:
	struct FSynchedActionInfo                     SynchedActionInfo;                                 // 0x0008(0x0030)(Edit, NoDestructor, NativeAccessSpecifierPublic)
	uint8                                         Pad_38[0x8];                                       // 0x0038(0x0008)(Fixing Size After Last Property [ Dumper-8 ])
	struct FSynchedActionWarpPointInfo_Replicated SynchedActionWarpPointInfo;                        // 0x0040(0x00A0)(NoDestructor, ContainsInstancedReference, NativeAccessSpecifierPublic)
	struct FVector                                TargetLocation;                                    // 0x00E0(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FRotator                               TargetRotation;                                    // 0x00F8(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
	TWeakObjectPtr<class AActor>                  RefActor;                                          // 0x0110(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TWeakObjectPtr<class UPrimitiveComponent>     RefActorComponent;                                 // 0x0118(0x0008)(ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   RefActorBoneName;                                  // 0x0120(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EFortSynchedActionEndMovementMode             EndMovementMode;                                   // 0x0124(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bIsWindow;                                         // 0x0125(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_126[0x2];                                      // 0x0126(0x0002)(Fixing Struct Size After Last Property [ Dumper-8 ])
};
#pragma pack(pop)

}

