#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: CosmeticsFrameworkItems

#include "Basic.hpp"

#include "GameplayTags_structs.hpp"
#include "CosmeticsFrameworkItems_structs.hpp"


namespace SDK::Params
{

// Function CosmeticsFrameworkItems.CosmeticDataComponent.BP_AddOrOverrideProperty
// 0x000C (0x000C - 0x0000)
struct CosmeticDataComponent_BP_AddOrOverrideProperty final
{
public:
	struct FGameplayTag                           SlotTag;                                           // 0x0000(0x0004)(Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FCosmeticPropertyBase                  Property;                                          // 0x0004(0x0004)(ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0008(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9[0x3];                                        // 0x0009(0x0003)(Fixing Struct Size After Last Property [ Dumper-8 ])
};

// Function CosmeticsFrameworkItems.CosmeticDataComponent.BP_FindProperty
// 0x0010 (0x0010 - 0x0000)
struct CosmeticDataComponent_BP_FindProperty final
{
public:
	struct FGameplayTag                           SlotTag;                                           // 0x0000(0x0004)(Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FGameplayTag                           PropertyTag;                                       // 0x0004(0x0004)(Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FCosmeticPropertyBase                  OutProperty;                                       // 0x0008(0x0004)(Parm, OutParm, NoDestructor, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x000C(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_D[0x3];                                        // 0x000D(0x0003)(Fixing Struct Size After Last Property [ Dumper-8 ])
};

}

