#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: Curie

#include "Basic.hpp"

#include "GameplayTags_structs.hpp"
#include "Curie_structs.hpp"


namespace SDK::Params
{

// Function Curie.CurieInterface.OnCurieContainerAcquired_BP
// 0x0004 (0x0004 - 0x0000)
struct CurieInterface_OnCurieContainerAcquired_BP final
{
public:
	struct FCurieContainerHandle                  CurieContainerHandle;                              // 0x0000(0x0004)(ConstParm, Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function Curie.CurieInterface.OnCurieContainerReleased_BP
// 0x0004 (0x0004 - 0x0000)
struct CurieInterface_OnCurieContainerReleased_BP final
{
public:
	struct FCurieContainerHandle                  CurieContainerHandle;                              // 0x0000(0x0004)(ConstParm, Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function Curie.CurieInterface.OnCurieContainerReparented_BP
// 0x0004 (0x0004 - 0x0000)
struct CurieInterface_OnCurieContainerReparented_BP final
{
public:
	struct FCurieContainerHandle                  CurieContainerHandle;                              // 0x0000(0x0004)(ConstParm, Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function Curie.CurieInterface.OnCurieElementAttached_BP
// 0x0008 (0x0008 - 0x0000)
struct CurieInterface_OnCurieElementAttached_BP final
{
public:
	struct FCurieContainerHandle                  CurieContainerHandle;                              // 0x0000(0x0004)(ConstParm, Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FGameplayTag                           ElementTag;                                        // 0x0004(0x0004)(ConstParm, Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function Curie.CurieInterface.OnCurieElementDetached_BP
// 0x0008 (0x0008 - 0x0000)
struct CurieInterface_OnCurieElementDetached_BP final
{
public:
	struct FCurieContainerHandle                  CurieContainerHandle;                              // 0x0000(0x0004)(ConstParm, Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FGameplayTag                           ElementTag;                                        // 0x0004(0x0004)(ConstParm, Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function Curie.CurieInterface.OnCurieElementInteract_BP
// 0x0018 (0x0018 - 0x0000)
struct CurieInterface_OnCurieElementInteract_BP final
{
public:
	struct FCurieContainerHandle                  CurieContainerHandle;                              // 0x0000(0x0004)(ConstParm, Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FGameplayTag                           ElementTag;                                        // 0x0004(0x0004)(ConstParm, Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FCurieInteractParamsHandle             InteractParamsHandle;                              // 0x0008(0x0010)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
};

// Function Curie.CurieInterface.OnCurieElementInteractBegun_BP
// 0x0018 (0x0018 - 0x0000)
struct CurieInterface_OnCurieElementInteractBegun_BP final
{
public:
	struct FCurieContainerHandle                  CurieContainerHandle;                              // 0x0000(0x0004)(ConstParm, Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FGameplayTag                           ElementTag;                                        // 0x0004(0x0004)(ConstParm, Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FCurieInteractParamsHandle             InteractParamsHandle;                              // 0x0008(0x0010)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
};

// Function Curie.CurieInterface.OnCurieElementInteractEnded_BP
// 0x0018 (0x0018 - 0x0000)
struct CurieInterface_OnCurieElementInteractEnded_BP final
{
public:
	struct FCurieContainerHandle                  CurieContainerHandle;                              // 0x0000(0x0004)(ConstParm, Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FGameplayTag                           ElementTag;                                        // 0x0004(0x0004)(ConstParm, Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FCurieInteractParamsHandle             InteractParamsHandle;                              // 0x0008(0x0010)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
};

// Function Curie.CurieInterface.OnCurieStateAttached_BP
// 0x0008 (0x0008 - 0x0000)
struct CurieInterface_OnCurieStateAttached_BP final
{
public:
	struct FCurieContainerHandle                  CurieContainerHandle;                              // 0x0000(0x0004)(ConstParm, Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FGameplayTag                           StateTag;                                          // 0x0004(0x0004)(ConstParm, Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function Curie.CurieInterface.OnCurieStateDetached_BP
// 0x0008 (0x0008 - 0x0000)
struct CurieInterface_OnCurieStateDetached_BP final
{
public:
	struct FCurieContainerHandle                  CurieContainerHandle;                              // 0x0000(0x0004)(ConstParm, Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FGameplayTag                           StateTag;                                          // 0x0004(0x0004)(ConstParm, Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function Curie.CurieManager.BindDelegateForCurieElementAttached
// 0x0018 (0x0018 - 0x0000)
struct CurieManager_BindDelegateForCurieElementAttached final
{
public:
	class UObject*                                CurieOwner;                                        // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TDelegate<void(class UObject* Owner, const struct FCurieContainerHandle& ContainerHandle, const struct FGameplayTag& ElementIdentifier)> Delegate; // 0x0008(0x000C)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Struct Size After Last Property [ Dumper-8 ])
};

// Function Curie.CurieManager.BindDelegateForCurieElementBeginInteract
// 0x0018 (0x0018 - 0x0000)
struct CurieManager_BindDelegateForCurieElementBeginInteract final
{
public:
	class UObject*                                CurieOwner;                                        // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TDelegate<void(class UObject* Owner, const struct FCurieContainerHandle& ContainerHandle, const struct FGameplayTag& ElementIdentifier)> Delegate; // 0x0008(0x000C)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Struct Size After Last Property [ Dumper-8 ])
};

// Function Curie.CurieManager.BindDelegateForCurieElementDetached
// 0x0018 (0x0018 - 0x0000)
struct CurieManager_BindDelegateForCurieElementDetached final
{
public:
	class UObject*                                CurieOwner;                                        // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TDelegate<void(class UObject* Owner, const struct FCurieContainerHandle& ContainerHandle, const struct FGameplayTag& ElementIdentifier)> Delegate; // 0x0008(0x000C)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Struct Size After Last Property [ Dumper-8 ])
};

// Function Curie.CurieManager.BindDelegateForCurieElementEndInteract
// 0x0018 (0x0018 - 0x0000)
struct CurieManager_BindDelegateForCurieElementEndInteract final
{
public:
	class UObject*                                CurieOwner;                                        // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TDelegate<void(class UObject* Owner, const struct FCurieContainerHandle& ContainerHandle, const struct FGameplayTag& ElementIdentifier)> Delegate; // 0x0008(0x000C)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Struct Size After Last Property [ Dumper-8 ])
};

// Function Curie.CurieManager.BindDelegateForCurieElementInteract
// 0x0018 (0x0018 - 0x0000)
struct CurieManager_BindDelegateForCurieElementInteract final
{
public:
	class UObject*                                CurieOwner;                                        // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TDelegate<void(class UObject* Owner, const struct FCurieContainerHandle& ContainerHandle, const struct FGameplayTag& ElementIdentifier)> Delegate; // 0x0008(0x000C)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Struct Size After Last Property [ Dumper-8 ])
};

// Function Curie.CurieManager.BindDelegateForCurieStateAttached
// 0x0018 (0x0018 - 0x0000)
struct CurieManager_BindDelegateForCurieStateAttached final
{
public:
	class UObject*                                CurieOwner;                                        // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TDelegate<void(class UObject* Owner, const struct FCurieContainerHandle& ContainerHandle, const struct FGameplayTag& StateIdentifier)> Delegate; // 0x0008(0x000C)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Struct Size After Last Property [ Dumper-8 ])
};

// Function Curie.CurieManager.BindDelegateForCurieStateDetached
// 0x0018 (0x0018 - 0x0000)
struct CurieManager_BindDelegateForCurieStateDetached final
{
public:
	class UObject*                                CurieOwner;                                        // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TDelegate<void(class UObject* Owner, const struct FCurieContainerHandle& ContainerHandle, const struct FGameplayTag& StateIdentifier)> Delegate; // 0x0008(0x000C)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Struct Size After Last Property [ Dumper-8 ])
};

// Function Curie.CurieManager.HandleContainerOwnerDestroyed
// 0x0008 (0x0008 - 0x0000)
struct CurieManager_HandleContainerOwnerDestroyed final
{
public:
	class AActor*                                 OwnerActor;                                        // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function Curie.CurieManager.UnbindDelegateForCurieElementAttached
// 0x0018 (0x0018 - 0x0000)
struct CurieManager_UnbindDelegateForCurieElementAttached final
{
public:
	class UObject*                                CurieOwner;                                        // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TDelegate<void(class UObject* Owner, const struct FCurieContainerHandle& ContainerHandle, const struct FGameplayTag& ElementIdentifier)> Delegate; // 0x0008(0x000C)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Struct Size After Last Property [ Dumper-8 ])
};

// Function Curie.CurieManager.UnbindDelegateForCurieElementBeginInteract
// 0x0018 (0x0018 - 0x0000)
struct CurieManager_UnbindDelegateForCurieElementBeginInteract final
{
public:
	class UObject*                                CurieOwner;                                        // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TDelegate<void(class UObject* Owner, const struct FCurieContainerHandle& ContainerHandle, const struct FGameplayTag& ElementIdentifier)> Delegate; // 0x0008(0x000C)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Struct Size After Last Property [ Dumper-8 ])
};

// Function Curie.CurieManager.UnbindDelegateForCurieElementDetached
// 0x0018 (0x0018 - 0x0000)
struct CurieManager_UnbindDelegateForCurieElementDetached final
{
public:
	class UObject*                                CurieOwner;                                        // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TDelegate<void(class UObject* Owner, const struct FCurieContainerHandle& ContainerHandle, const struct FGameplayTag& ElementIdentifier)> Delegate; // 0x0008(0x000C)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Struct Size After Last Property [ Dumper-8 ])
};

// Function Curie.CurieManager.UnbindDelegateForCurieElementEndInteract
// 0x0018 (0x0018 - 0x0000)
struct CurieManager_UnbindDelegateForCurieElementEndInteract final
{
public:
	class UObject*                                CurieOwner;                                        // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TDelegate<void(class UObject* Owner, const struct FCurieContainerHandle& ContainerHandle, const struct FGameplayTag& ElementIdentifier)> Delegate; // 0x0008(0x000C)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Struct Size After Last Property [ Dumper-8 ])
};

// Function Curie.CurieManager.UnbindDelegateForCurieElementInteract
// 0x0018 (0x0018 - 0x0000)
struct CurieManager_UnbindDelegateForCurieElementInteract final
{
public:
	class UObject*                                CurieOwner;                                        // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TDelegate<void(class UObject* Owner, const struct FCurieContainerHandle& ContainerHandle, const struct FGameplayTag& ElementIdentifier)> Delegate; // 0x0008(0x000C)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Struct Size After Last Property [ Dumper-8 ])
};

// Function Curie.CurieManager.UnbindDelegateForCurieStateAttached
// 0x0018 (0x0018 - 0x0000)
struct CurieManager_UnbindDelegateForCurieStateAttached final
{
public:
	class UObject*                                CurieOwner;                                        // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TDelegate<void(class UObject* Owner, const struct FCurieContainerHandle& ContainerHandle, const struct FGameplayTag& StateIdentifier)> Delegate; // 0x0008(0x000C)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Struct Size After Last Property [ Dumper-8 ])
};

// Function Curie.CurieManager.UnbindDelegateForCurieStateDetached
// 0x0018 (0x0018 - 0x0000)
struct CurieManager_UnbindDelegateForCurieStateDetached final
{
public:
	class UObject*                                CurieOwner;                                        // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TDelegate<void(class UObject* Owner, const struct FCurieContainerHandle& ContainerHandle, const struct FGameplayTag& StateIdentifier)> Delegate; // 0x0008(0x000C)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Struct Size After Last Property [ Dumper-8 ])
};

}

