#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: DiamondStatePip

#include "Basic.hpp"

#include "DiamondStatePip_classes.hpp"
#include "DiamondStatePip_parameters.hpp"


namespace SDK
{

// Function DiamondStatePip.DiamondStatePip_C.SetSelectedState
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsSelected                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UDiamondStatePip_C::SetSelectedState(bool IsSelected)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DiamondStatePip_C", "SetSelectedState");

	Params::DiamondStatePip_C_SetSelectedState Parms{};

	Parms.IsSelected = IsSelected;

	UObject::ProcessEvent(Func, &Parms);
}


// Function DiamondStatePip.DiamondStatePip_C.SetHoverState
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsHovered_0                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UDiamondStatePip_C::SetHoverState(bool IsHovered_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DiamondStatePip_C", "SetHoverState");

	Params::DiamondStatePip_C_SetHoverState Parms{};

	Parms.IsHovered_0 = IsHovered_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function DiamondStatePip.DiamondStatePip_C.ResetState
// (Public, BlueprintCallable, BlueprintEvent)

void UDiamondStatePip_C::ResetState()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DiamondStatePip_C", "ResetState");

	UObject::ProcessEvent(Func, nullptr);
}


// Function DiamondStatePip.DiamondStatePip_C.ExecuteUbergraph_DiamondStatePip
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UDiamondStatePip_C::ExecuteUbergraph_DiamondStatePip(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DiamondStatePip_C", "ExecuteUbergraph_DiamondStatePip");

	Params::DiamondStatePip_C_ExecuteUbergraph_DiamondStatePip Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function DiamondStatePip.DiamondStatePip_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UDiamondStatePip_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DiamondStatePip_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}

}

