#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: DualBladeMenu

#include "Basic.hpp"

#include "DualBladeMenu_classes.hpp"
#include "DualBladeMenu_parameters.hpp"


namespace SDK
{

// Function DualBladeMenu.DualBladeMenu_C.OnInitialized
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UDualBladeMenu_C::OnInitialized()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DualBladeMenu_C", "OnInitialized");

	UObject::ProcessEvent(Func, nullptr);
}


// Function DualBladeMenu.DualBladeMenu_C.OnFullScreenWidgetCreated
// (Event, Protected, BlueprintEvent)
// Parameters:
// class UWidget*                          NewWidget                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UDualBladeMenu_C::OnFullScreenWidgetCreated(class UWidget* NewWidget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DualBladeMenu_C", "OnFullScreenWidgetCreated");

	Params::DualBladeMenu_C_OnFullScreenWidgetCreated Parms{};

	Parms.NewWidget = NewWidget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function DualBladeMenu.DualBladeMenu_C.ExecuteUbergraph_DualBladeMenu
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UDualBladeMenu_C::ExecuteUbergraph_DualBladeMenu(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DualBladeMenu_C", "ExecuteUbergraph_DualBladeMenu");

	Params::DualBladeMenu_C_ExecuteUbergraph_DualBladeMenu Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

