#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: E_UI_ButtonVisualType

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum E_UI_ButtonVisualType.E_UI_ButtonVisualType
// NumValues: 0x0004
enum class E_UI_ButtonVisualType : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	NewEnumerator2                           = 2,
	E_UI_MAX                                 = 3,
};

}

