#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: EUW_FunctionLibrary

#include "Basic.hpp"

#include "EUW_FunctionLibrary_classes.hpp"
#include "EUW_FunctionLibrary_parameters.hpp"


namespace SDK
{

// Function EUW_FunctionLibrary.EUW_FunctionLibrary_C.PointVector PointVector Intersection
// (Static, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FVector&                   FirstVectorOrigin                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FVector&                   FirstVectorDirection                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FVector&                   SecondVectorOrigin                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FVector&                   SecondVectorDirection                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// struct FVector*                         IntersectionPoint                                      (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool*                                   DoVectorsInersect_                                     (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UEUW_FunctionLibrary_C::PointVector_PointVector_Intersection(const struct FVector& FirstVectorOrigin, const struct FVector& FirstVectorDirection, const struct FVector& SecondVectorOrigin, const struct FVector& SecondVectorDirection, class UObject* __WorldContext, struct FVector* IntersectionPoint, bool* DoVectorsInersect_)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("EUW_FunctionLibrary_C", "PointVector PointVector Intersection");

	Params::EUW_FunctionLibrary_C_PointVector_PointVector_Intersection Parms{};

	Parms.FirstVectorOrigin = std::move(FirstVectorOrigin);
	Parms.FirstVectorDirection = std::move(FirstVectorDirection);
	Parms.SecondVectorOrigin = std::move(SecondVectorOrigin);
	Parms.SecondVectorDirection = std::move(SecondVectorDirection);
	Parms.__WorldContext = __WorldContext;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	if (IntersectionPoint != nullptr)
		*IntersectionPoint = std::move(Parms.IntersectionPoint);

	if (DoVectorsInersect_ != nullptr)
		*DoVectorsInersect_ = Parms.DoVectorsInersect_;
}


// Function EUW_FunctionLibrary.EUW_FunctionLibrary_C.Lerp Vector 2D
// (Static, Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// const struct FVector2D&                 A                                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FVector2D&                 B                                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  Alpha                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// struct FVector2D                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

struct FVector2D UEUW_FunctionLibrary_C::Lerp_Vector_2D(const struct FVector2D& A, const struct FVector2D& B, double Alpha, class UObject* __WorldContext)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("EUW_FunctionLibrary_C", "Lerp Vector 2D");

	Params::EUW_FunctionLibrary_C_Lerp_Vector_2D Parms{};

	Parms.A = std::move(A);
	Parms.B = std::move(B);
	Parms.Alpha = Alpha;
	Parms.__WorldContext = __WorldContext;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function EUW_FunctionLibrary.EUW_FunctionLibrary_C.Create SliderLabel
// (Static, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FPaintContext&             OnPaintContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// class USlider*                          Slider                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// const struct FVector2D&                 PositionalShift                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const class FString&                    Label                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// const struct FLinearColor&              Label_Color                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   FontSize                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// struct FPaintContext*                   ContextOut                                             (Parm, OutParm, NoDestructor)

void UEUW_FunctionLibrary_C::Create_SliderLabel(const struct FPaintContext& OnPaintContext, class USlider* Slider, const struct FVector2D& PositionalShift, const class FString& Label, const struct FLinearColor& Label_Color, int32 FontSize, class UObject* __WorldContext, struct FPaintContext* ContextOut)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("EUW_FunctionLibrary_C", "Create SliderLabel");

	Params::EUW_FunctionLibrary_C_Create_SliderLabel Parms{};

	Parms.OnPaintContext = std::move(OnPaintContext);
	Parms.Slider = Slider;
	Parms.PositionalShift = std::move(PositionalShift);
	Parms.Label = std::move(Label);
	Parms.Label_Color = std::move(Label_Color);
	Parms.FontSize = FontSize;
	Parms.__WorldContext = __WorldContext;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	if (ContextOut != nullptr)
		*ContextOut = std::move(Parms.ContextOut);
}

}

