#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: FortHUDElementWrapper

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass FortHUDElementWrapper.FortHUDElementWrapper_C
// 0x0008 (0x0328 - 0x0320)
class UFortHUDElementWrapper_C final : public UFortHUDElementWidget
{
public:
	class UNamedSlot*                             Content;                                           // 0x0320(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"FortHUDElementWrapper_C">();
	}
	static class UFortHUDElementWrapper_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFortHUDElementWrapper_C>();
	}
};

}

