#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GA_Athena_LowGravity_GlitchPassive

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_Athena_LowGravity_GlitchPassive.GA_Athena_LowGravity_GlitchPassive_C
// 0x0008 (0x0B48 - 0x0B40)
class UGA_Athena_LowGravity_GlitchPassive_C final : public UFortGameplayAbility
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0B40(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_GA_Athena_LowGravity_GlitchPassive(int32 EntryPoint);
	void FailedToActivatePassiveAbility(const struct FGameplayAbilityActorInfo& ActorInfo);
	void K2_ActivateAbility();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GA_Athena_LowGravity_GlitchPassive_C">();
	}
	static class UGA_Athena_LowGravity_GlitchPassive_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_Athena_LowGravity_GlitchPassive_C>();
	}
};

}

