#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GAB_Melee_GenericCombo

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "GAB_Melee_Generic_EventGraph_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GAB_Melee_GenericCombo.GAB_Melee_GenericCombo_C
// 0x0010 (0x0B88 - 0x0B78)
class UGAB_Melee_GenericCombo_C : public UGAB_Melee_Generic_EventGraph_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_GAB_Melee_GenericCombo_C;           // 0x0B78(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	double                                        OriginalMontagePlayRate;                           // 0x0B80(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void Triggered_C69ED31E4DA3D5C32C2E1EABFD10F38B(const struct FGameplayAbilityTargetDataHandle& TargetData, const struct FGameplayTag& ApplicationTag);
	void K2_OnEndAbility(bool bWasCancelled);
	void K2_ActivateAbility();
	void ExecuteUbergraph_GAB_Melee_GenericCombo(int32 EntryPoint);
	void Completed_C69ED31E4DA3D5C32C2E1EABFD10F38B(const struct FGameplayAbilityTargetDataHandle& TargetData, const struct FGameplayTag& ApplicationTag);
	void Cancelled_C69ED31E4DA3D5C32C2E1EABFD10F38B(const struct FGameplayAbilityTargetDataHandle& TargetData, const struct FGameplayTag& ApplicationTag);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GAB_Melee_GenericCombo_C">();
	}
	static class UGAB_Melee_GenericCombo_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGAB_Melee_GenericCombo_C>();
	}
};

}

