#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GCNL_ZeroPoint_Crystal_ActiveEffect

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GCNL_ZeroPoint_Crystal_ActiveEffect.GCNL_ZeroPoint_Crystal_ActiveEffect_C
// 0x0000 (0x09B0 - 0x09B0)
class AGCNL_ZeroPoint_Crystal_ActiveEffect_C final : public AFortGameplayCueNotify_Loop
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GCNL_ZeroPoint_Crystal_ActiveEffect_C">();
	}
	static class AGCNL_ZeroPoint_Crystal_ActiveEffect_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AGCNL_ZeroPoint_Crystal_ActiveEffect_C>();
	}
};

}

