#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GE_Hero_PulsingEnergyCost

#include "Basic.hpp"

#include "GET_EnergyCost_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_Hero_PulsingEnergyCost.GE_Hero_PulsingEnergyCost_C
// 0x0000 (0x0A68 - 0x0A68)
class UGE_Hero_PulsingEnergyCost_C final : public UGET_EnergyCost_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GE_Hero_PulsingEnergyCost_C">();
	}
	static class UGE_Hero_PulsingEnergyCost_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_Hero_PulsingEnergyCost_C>();
	}
};

}

