#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GE_RiftSpawnerDamgePerSpawn_Static

#include "Basic.hpp"

#include "GET_DamagePercent_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_RiftSpawnerDamgePerSpawn_Static.GE_RiftSpawnerDamgePerSpawn_Static_C
// 0x0000 (0x0A68 - 0x0A68)
class UGE_RiftSpawnerDamgePerSpawn_Static_C final : public UGET_DamagePercent_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GE_RiftSpawnerDamgePerSpawn_Static_C">();
	}
	static class UGE_RiftSpawnerDamgePerSpawn_Static_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_RiftSpawnerDamgePerSpawn_Static_C>();
	}
};

}

