#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GrindRail_Player_LayerAnimBP

#include "Basic.hpp"

#include "GrindRail_Player_LayerAnimBP_classes.hpp"
#include "GrindRail_Player_LayerAnimBP_parameters.hpp"


namespace SDK
{

// Function GrindRail_Player_LayerAnimBP.GrindRail_Player_LayerAnimBP_C.MovementMode_SourcePose
// (HasOutParams, BlueprintCallable)
// Parameters:
// const struct FPoseLink&                 InSourcePoseBase                                       (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FPoseLink*                       MovementMode_SourcePose_0                              (Parm, OutParm, NoDestructor)

void UGrindRail_Player_LayerAnimBP_C::MovementMode_SourcePose(const struct FPoseLink& InSourcePoseBase, struct FPoseLink* MovementMode_SourcePose_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GrindRail_Player_LayerAnimBP_C", "MovementMode_SourcePose");

	Params::GrindRail_Player_LayerAnimBP_C_MovementMode_SourcePose Parms{};

	Parms.InSourcePoseBase = std::move(InSourcePoseBase);

	UObject::ProcessEvent(Func, &Parms);

	if (MovementMode_SourcePose_0 != nullptr)
		*MovementMode_SourcePose_0 = std::move(Parms.MovementMode_SourcePose_0);
}


// Function GrindRail_Player_LayerAnimBP.GrindRail_Player_LayerAnimBP_C.MovementMode_LowerBodyOverride
// (HasOutParams, BlueprintCallable)
// Parameters:
// const struct FPoseLink&                 InLowerBodyPose                                        (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// const struct FPoseLink&                 InSourcePose                                           (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FPoseLink*                       MovementMode_LowerBodyOverride_0                       (Parm, OutParm, NoDestructor)

void UGrindRail_Player_LayerAnimBP_C::MovementMode_LowerBodyOverride(const struct FPoseLink& InLowerBodyPose, const struct FPoseLink& InSourcePose, struct FPoseLink* MovementMode_LowerBodyOverride_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GrindRail_Player_LayerAnimBP_C", "MovementMode_LowerBodyOverride");

	Params::GrindRail_Player_LayerAnimBP_C_MovementMode_LowerBodyOverride Parms{};

	Parms.InLowerBodyPose = std::move(InLowerBodyPose);
	Parms.InSourcePose = std::move(InSourcePose);

	UObject::ProcessEvent(Func, &Parms);

	if (MovementMode_LowerBodyOverride_0 != nullptr)
		*MovementMode_LowerBodyOverride_0 = std::move(Parms.MovementMode_LowerBodyOverride_0);
}


// Function GrindRail_Player_LayerAnimBP.GrindRail_Player_LayerAnimBP_C.MovementMode_LocomotionAdditives
// (HasOutParams, BlueprintCallable)
// Parameters:
// const struct FPoseLink&                 InLocomotionAdditivesPose                              (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FPoseLink*                       MovementMode_LocomotionAdditives_0                     (Parm, OutParm, NoDestructor)

void UGrindRail_Player_LayerAnimBP_C::MovementMode_LocomotionAdditives(const struct FPoseLink& InLocomotionAdditivesPose, struct FPoseLink* MovementMode_LocomotionAdditives_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GrindRail_Player_LayerAnimBP_C", "MovementMode_LocomotionAdditives");

	Params::GrindRail_Player_LayerAnimBP_C_MovementMode_LocomotionAdditives Parms{};

	Parms.InLocomotionAdditivesPose = std::move(InLocomotionAdditivesPose);

	UObject::ProcessEvent(Func, &Parms);

	if (MovementMode_LocomotionAdditives_0 != nullptr)
		*MovementMode_LocomotionAdditives_0 = std::move(Parms.MovementMode_LocomotionAdditives_0);
}


// Function GrindRail_Player_LayerAnimBP.GrindRail_Player_LayerAnimBP_C.MovementMode_FullBodyOverride
// (HasOutParams, BlueprintCallable)
// Parameters:
// const struct FPoseLink&                 InputPoseFullBody                                      (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FPoseLink*                       MovementMode_FullBodyOverride_0                        (Parm, OutParm, NoDestructor)

void UGrindRail_Player_LayerAnimBP_C::MovementMode_FullBodyOverride(const struct FPoseLink& InputPoseFullBody, struct FPoseLink* MovementMode_FullBodyOverride_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GrindRail_Player_LayerAnimBP_C", "MovementMode_FullBodyOverride");

	Params::GrindRail_Player_LayerAnimBP_C_MovementMode_FullBodyOverride Parms{};

	Parms.InputPoseFullBody = std::move(InputPoseFullBody);

	UObject::ProcessEvent(Func, &Parms);

	if (MovementMode_FullBodyOverride_0 != nullptr)
		*MovementMode_FullBodyOverride_0 = std::move(Parms.MovementMode_FullBodyOverride_0);
}


// Function GrindRail_Player_LayerAnimBP.GrindRail_Player_LayerAnimBP_C.MovementMode_FinalPoseOverride
// (HasOutParams, BlueprintCallable)
// Parameters:
// const struct FPoseLink&                 InFinalPose                                            (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FPoseLink*                       MovementMode_FinalPoseOverride_0                       (Parm, OutParm, NoDestructor)

void UGrindRail_Player_LayerAnimBP_C::MovementMode_FinalPoseOverride(const struct FPoseLink& InFinalPose, struct FPoseLink* MovementMode_FinalPoseOverride_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GrindRail_Player_LayerAnimBP_C", "MovementMode_FinalPoseOverride");

	Params::GrindRail_Player_LayerAnimBP_C_MovementMode_FinalPoseOverride Parms{};

	Parms.InFinalPose = std::move(InFinalPose);

	UObject::ProcessEvent(Func, &Parms);

	if (MovementMode_FinalPoseOverride_0 != nullptr)
		*MovementMode_FinalPoseOverride_0 = std::move(Parms.MovementMode_FinalPoseOverride_0);
}


// Function GrindRail_Player_LayerAnimBP.GrindRail_Player_LayerAnimBP_C.MovementMode_AimOffset
// (HasOutParams, BlueprintCallable)
// Parameters:
// const struct FPoseLink&                 InAimOffsetsPose                                       (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// const struct FPoseLink&                 InSourcePosePreAimOffsets                              (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FPoseLink*                       MovementMode_AimOffset_0                               (Parm, OutParm, NoDestructor)

void UGrindRail_Player_LayerAnimBP_C::MovementMode_AimOffset(const struct FPoseLink& InAimOffsetsPose, const struct FPoseLink& InSourcePosePreAimOffsets, struct FPoseLink* MovementMode_AimOffset_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GrindRail_Player_LayerAnimBP_C", "MovementMode_AimOffset");

	Params::GrindRail_Player_LayerAnimBP_C_MovementMode_AimOffset Parms{};

	Parms.InAimOffsetsPose = std::move(InAimOffsetsPose);
	Parms.InSourcePosePreAimOffsets = std::move(InSourcePosePreAimOffsets);

	UObject::ProcessEvent(Func, &Parms);

	if (MovementMode_AimOffset_0 != nullptr)
		*MovementMode_AimOffset_0 = std::move(Parms.MovementMode_AimOffset_0);
}


// Function GrindRail_Player_LayerAnimBP.GrindRail_Player_LayerAnimBP_C.LocomotionAdditiveGroup
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FPoseLink&                 InPoseLocomotionAdditive                               (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FPoseLink*                       LocomotionAdditiveGroup_0                              (Parm, OutParm, NoDestructor)

void UGrindRail_Player_LayerAnimBP_C::LocomotionAdditiveGroup(const struct FPoseLink& InPoseLocomotionAdditive, struct FPoseLink* LocomotionAdditiveGroup_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GrindRail_Player_LayerAnimBP_C", "LocomotionAdditiveGroup");

	Params::GrindRail_Player_LayerAnimBP_C_LocomotionAdditiveGroup Parms{};

	Parms.InPoseLocomotionAdditive = std::move(InPoseLocomotionAdditive);

	UObject::ProcessEvent(Func, &Parms);

	if (LocomotionAdditiveGroup_0 != nullptr)
		*LocomotionAdditiveGroup_0 = std::move(Parms.LocomotionAdditiveGroup_0);
}


// Function GrindRail_Player_LayerAnimBP.GrindRail_Player_LayerAnimBP_C.ExecuteUbergraph_GrindRail_Player_LayerAnimBP
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGrindRail_Player_LayerAnimBP_C::ExecuteUbergraph_GrindRail_Player_LayerAnimBP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GrindRail_Player_LayerAnimBP_C", "ExecuteUbergraph_GrindRail_Player_LayerAnimBP");

	Params::GrindRail_Player_LayerAnimBP_C_ExecuteUbergraph_GrindRail_Player_LayerAnimBP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GrindRail_Player_LayerAnimBP.GrindRail_Player_LayerAnimBP_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink*                       AnimGraph_0                                            (Parm, OutParm, NoDestructor)

void UGrindRail_Player_LayerAnimBP_C::AnimGraph(struct FPoseLink* AnimGraph_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GrindRail_Player_LayerAnimBP_C", "AnimGraph");

	Params::GrindRail_Player_LayerAnimBP_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (AnimGraph_0 != nullptr)
		*AnimGraph_0 = std::move(Parms.AnimGraph_0);
}

}

