#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: KoalaUI

#include "Basic.hpp"

#include "FortniteUI_structs.hpp"
#include "FortniteUI_classes.hpp"
#include "KoalaUI_structs.hpp"
#include "CommonUI_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// Class KoalaUI.FortGameSettingRegistryExtension_Koala
// 0x0040 (0x0068 - 0x0028)
class UFortGameSettingRegistryExtension_Koala final : public UFortGameSettingRegistryExtension
{
public:
	uint8                                         Pad_28[0x8];                                       // 0x0028(0x0008)(Fixing Size After Last Property [ Dumper-8 ])
	struct FFortSettingNameExtensions             SettingExtensions;                                 // 0x0030(0x0018)(Edit, NativeAccessSpecifierPrivate)
	uint8                                         Pad_48[0x20];                                      // 0x0048(0x0020)(Fixing Struct Size After Last Property [ Dumper-8 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"FortGameSettingRegistryExtension_Koala">();
	}
	static class UFortGameSettingRegistryExtension_Koala* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFortGameSettingRegistryExtension_Koala>();
	}
};

// Class KoalaUI.FortSidebarPanelKoala
// 0x0038 (0x0430 - 0x03F8)
class UFortSidebarPanelKoala : public UCommonActivatableWidget
{
public:
	uint8                                         Pad_3F8[0x18];                                     // 0x03F8(0x0018)(Fixing Size After Last Property [ Dumper-8 ])
	class UCommonButtonBase*                      Button_KoalaDummy;                                 // 0x0410(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class UFortLazyImage*                         QrCodeImage;                                       // 0x0418(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class FString                                 QRCodeURL;                                         // 0x0420(0x0010)(Edit, ZeroConstructor, DisableEditOnInstance, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)

public:
	void OnConnectionChanged(bool bConnected);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"FortSidebarPanelKoala">();
	}
	static class UFortSidebarPanelKoala* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFortSidebarPanelKoala>();
	}
};

// Class KoalaUI.FortUIGameFeatureAction_AttemptKoalaModal
// 0x0038 (0x0068 - 0x0030)
class UFortUIGameFeatureAction_AttemptKoalaModal final : public UFortUIGameFeatureAction_PostFrontendFlowActions
{
public:
	TSoftClassPtr<class UClass>                   KoalaGraphicsModalClass;                           // 0x0030(0x0020)(Edit, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_50[0x18];                                      // 0x0050(0x0018)(Fixing Struct Size After Last Property [ Dumper-8 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"FortUIGameFeatureAction_AttemptKoalaModal">();
	}
	static class UFortUIGameFeatureAction_AttemptKoalaModal* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFortUIGameFeatureAction_AttemptKoalaModal>();
	}
};

// Class KoalaUI.KoalaGraphicsModal
// 0x0028 (0x0420 - 0x03F8)
class UKoalaGraphicsModal final : public UCommonActivatableWidget
{
public:
	uint8                                         Pad_3F8[0x18];                                     // 0x03F8(0x0018)(Fixing Size After Last Property [ Dumper-8 ])
	class UCommonButtonBase*                      Button_KeepEnabled;                                // 0x0410(0x0008)(ExportObject, ZeroConstructor, InstancedReference, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	class UCommonButtonBase*                      Button_Disable;                                    // 0x0418(0x0008)(ExportObject, ZeroConstructor, InstancedReference, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPrivate)

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"KoalaGraphicsModal">();
	}
	static class UKoalaGraphicsModal* GetDefaultObj()
	{
		return GetDefaultObjImpl<UKoalaGraphicsModal>();
	}
};

// Class KoalaUI.KoalaHUDWidget
// 0x0158 (0x0550 - 0x03F8)
class UKoalaHUDWidget final : public UCommonActivatableWidget
{
public:
	uint8                                         Pad_3F8[0x8];                                      // 0x03F8(0x0008)(Fixing Size After Last Property [ Dumper-8 ])
	float                                         ClipDebounceTime;                                  // 0x0400(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	float                                         PlayerKilledPlayerReminderTime;                    // 0x0404(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	float                                         MatchEndedReminderTime;                            // 0x0408(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	float                                         ClipReminderCooldownTime;                          // 0x040C(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	float                                         EliminationClipReminderDelayTime;                  // 0x0410(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_414[0x4];                                      // 0x0414(0x0004)(Fixing Size After Last Property [ Dumper-8 ])
	class USoundSubmix*                           ClipAudioSubmix;                                   // 0x0418(0x0008)(Edit, ZeroConstructor, DisableEditOnInstance, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class UCommonActionWidget*                    ClipActionWidget;                                  // 0x0420(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	struct FDataTableRowHandle                    ClipObjectInputAction;                             // 0x0428(0x0010)(Edit, NoDestructor, NativeAccessSpecifierPrivate)
	uint8                                         Pad_438[0x8];                                      // 0x0438(0x0008)(Fixing Size After Last Property [ Dumper-8 ])
	TMap<int32, struct FKoalaClipInfo>            ClipTracker;                                       // 0x0440(0x0050)(NativeAccessSpecifierPrivate)
	uint8                                         Pad_490[0x8];                                      // 0x0490(0x0008)(Fixing Size After Last Property [ Dumper-8 ])
	int32                                         LastClipID;                                        // 0x0498(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_49C[0x16];                                     // 0x049C(0x0016)(Fixing Size After Last Property [ Dumper-8 ])
	EKoalaMockClipMode                            MockClipMode;                                      // 0x04B2(0x0001)(Edit, ZeroConstructor, Config, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_4B3[0x1];                                      // 0x04B3(0x0001)(Fixing Size After Last Property [ Dumper-8 ])
	int32                                         MockClipUploadShortTime;                           // 0x04B4(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	int32                                         MockClipUploadLongTime;                            // 0x04B8(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	int32                                         MockClipCreateShortTime;                           // 0x04BC(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	int32                                         MockClipCreateLongTime;                            // 0x04C0(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_4C4[0x8C];                                     // 0x04C4(0x008C)(Fixing Struct Size After Last Property [ Dumper-8 ])

public:
	int32 GetTrackedClipCount();
	void HandleLocalPlayerKilledPlayer(const class AFortPlayerStateAthena* Player);
	void HandlePlayerMatchWon();
	void HandlePlayerPawnEmoteStopped(const class UFortItemDefinition* MontageItemDef, class AFortPawn* PawnEmoting);
	void OnAvailabilityChanged(EKoalaAvailability Availability);
	void OnClipStatusChanged(int32 InClipID, EKoalaClipStatus InClipStatus, float InUploadProgress);
	void OnConnectionChanged(EKoalaConnectionStatus InStatus);
	void OnInputComplete();
	void OnInputProgress(float Progress);
	void OnRecordingStatusChanged(EKoalaRecording InRecordingStatus);
	void OnReminderEnded();
	void OnReminderTimerStarted(float Time);
	void OnTouchAreaMouseDown();
	void RegisterClipButtonInput();
	void UnregisterClipButtonInput();

	int32 GetUploadingClipCount() const;

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"KoalaHUDWidget">();
	}
	static class UKoalaHUDWidget* GetDefaultObj()
	{
		return GetDefaultObjImpl<UKoalaHUDWidget>();
	}
};

// Class KoalaUI.KoalaMainMenuButton
// 0x0010 (0x1610 - 0x1600)
class UKoalaMainMenuButton final : public UFortMainMenuButtonExtension
{
public:
	uint8                                         Pad_1600[0x10];                                    // 0x1600(0x0010)(Fixing Struct Size After Last Property [ Dumper-8 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"KoalaMainMenuButton">();
	}
	static class UKoalaMainMenuButton* GetDefaultObj()
	{
		return GetDefaultObjImpl<UKoalaMainMenuButton>();
	}
};

// Class KoalaUI.KoalaSettingDetailExtension
// 0x0008 (0x02C8 - 0x02C0)
class UKoalaSettingDetailExtension final : public UFortSettingDetailExtension
{
public:
	uint8                                         Pad_2C0[0x8];                                      // 0x02C0(0x0008)(Fixing Struct Size After Last Property [ Dumper-8 ])

public:
	void OnAvailabilityChanged(bool bAvailable);
	void OnConnectionChanged(bool bConnected);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"KoalaSettingDetailExtension">();
	}
	static class UKoalaSettingDetailExtension* GetDefaultObj()
	{
		return GetDefaultObjImpl<UKoalaSettingDetailExtension>();
	}
};

}

