#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: LWP_RiftEncounter_Parent

#include "Basic.hpp"

#include "LWP_RiftEncounter_Parent_classes.hpp"
#include "LWP_RiftEncounter_Parent_parameters.hpp"


namespace SDK
{

// Function LWP_RiftEncounter_Parent.LWP_RiftEncounter_Parent_C.TriggerPreSpawnVFX
// (Net, NetMulticast, BlueprintCallable, BlueprintEvent)

void ALWP_RiftEncounter_Parent_C::TriggerPreSpawnVFX()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LWP_RiftEncounter_Parent_C", "TriggerPreSpawnVFX");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LWP_RiftEncounter_Parent.LWP_RiftEncounter_Parent_C.StartEncounter
// (BlueprintCallable, BlueprintEvent)

void ALWP_RiftEncounter_Parent_C::StartEncounter()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LWP_RiftEncounter_Parent_C", "StartEncounter");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LWP_RiftEncounter_Parent.LWP_RiftEncounter_Parent_C.StartAnticipationCameraShake
// (BlueprintCallable, BlueprintEvent)

void ALWP_RiftEncounter_Parent_C::StartAnticipationCameraShake()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LWP_RiftEncounter_Parent_C", "StartAnticipationCameraShake");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LWP_RiftEncounter_Parent.LWP_RiftEncounter_Parent_C.SpawnLingeringVFX
// (BlueprintCallable, BlueprintEvent)

void ALWP_RiftEncounter_Parent_C::SpawnLingeringVFX()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LWP_RiftEncounter_Parent_C", "SpawnLingeringVFX");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LWP_RiftEncounter_Parent.LWP_RiftEncounter_Parent_C.SpawnAudioBurst
// (BlueprintCallable, BlueprintEvent)

void ALWP_RiftEncounter_Parent_C::SpawnAudioBurst()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LWP_RiftEncounter_Parent_C", "SpawnAudioBurst");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LWP_RiftEncounter_Parent.LWP_RiftEncounter_Parent_C.SpawnAncitipationVFX
// (Public, BlueprintCallable, BlueprintEvent)

void ALWP_RiftEncounter_Parent_C::SpawnAncitipationVFX()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LWP_RiftEncounter_Parent_C", "SpawnAncitipationVFX");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LWP_RiftEncounter_Parent.LWP_RiftEncounter_Parent_C.ReceiveEndPlay
// (Event, Protected, BlueprintEvent)
// Parameters:
// EEndPlayReason                          EndPlayReason                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ALWP_RiftEncounter_Parent_C::ReceiveEndPlay(EEndPlayReason EndPlayReason)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LWP_RiftEncounter_Parent_C", "ReceiveEndPlay");

	Params::LWP_RiftEncounter_Parent_C_ReceiveEndPlay Parms{};

	Parms.EndPlayReason = EndPlayReason;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LWP_RiftEncounter_Parent.LWP_RiftEncounter_Parent_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ALWP_RiftEncounter_Parent_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LWP_RiftEncounter_Parent_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LWP_RiftEncounter_Parent.LWP_RiftEncounter_Parent_C.PushBackPlayers
// (BlueprintCallable, BlueprintEvent)

void ALWP_RiftEncounter_Parent_C::PushBackPlayers()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LWP_RiftEncounter_Parent_C", "PushBackPlayers");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LWP_RiftEncounter_Parent.LWP_RiftEncounter_Parent_C.PostSpawnEvents
// (BlueprintCallable, BlueprintEvent)

void ALWP_RiftEncounter_Parent_C::PostSpawnEvents()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LWP_RiftEncounter_Parent_C", "PostSpawnEvents");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LWP_RiftEncounter_Parent.LWP_RiftEncounter_Parent_C.OnRep_LevelIsVisble
// (BlueprintCallable, BlueprintEvent)

void ALWP_RiftEncounter_Parent_C::OnRep_LevelIsVisble()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LWP_RiftEncounter_Parent_C", "OnRep_LevelIsVisble");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LWP_RiftEncounter_Parent.LWP_RiftEncounter_Parent_C.OnRep_AllowVFXToSpawn
// (BlueprintCallable, BlueprintEvent)

void ALWP_RiftEncounter_Parent_C::OnRep_AllowVFXToSpawn()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LWP_RiftEncounter_Parent_C", "OnRep_AllowVFXToSpawn");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LWP_RiftEncounter_Parent.LWP_RiftEncounter_Parent_C.OnBuildingsDestroyed
// (BlueprintCallable, BlueprintEvent)

void ALWP_RiftEncounter_Parent_C::OnBuildingsDestroyed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LWP_RiftEncounter_Parent_C", "OnBuildingsDestroyed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LWP_RiftEncounter_Parent.LWP_RiftEncounter_Parent_C.ExecuteUbergraph_LWP_RiftEncounter_Parent
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ALWP_RiftEncounter_Parent_C::ExecuteUbergraph_LWP_RiftEncounter_Parent(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LWP_RiftEncounter_Parent_C", "ExecuteUbergraph_LWP_RiftEncounter_Parent");

	Params::LWP_RiftEncounter_Parent_C_ExecuteUbergraph_LWP_RiftEncounter_Parent Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LWP_RiftEncounter_Parent.LWP_RiftEncounter_Parent_C.DecalAnimation__UpdateFunc
// (BlueprintEvent)

void ALWP_RiftEncounter_Parent_C::DecalAnimation__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LWP_RiftEncounter_Parent_C", "DecalAnimation__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LWP_RiftEncounter_Parent.LWP_RiftEncounter_Parent_C.DecalAnimation__FinishedFunc
// (BlueprintEvent)

void ALWP_RiftEncounter_Parent_C::DecalAnimation__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LWP_RiftEncounter_Parent_C", "DecalAnimation__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LWP_RiftEncounter_Parent.LWP_RiftEncounter_Parent_C.GetTeleportLocation
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// struct FVector*                         Location                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ALWP_RiftEncounter_Parent_C::GetTeleportLocation(struct FVector* Location) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LWP_RiftEncounter_Parent_C", "GetTeleportLocation");

	Params::LWP_RiftEncounter_Parent_C_GetTeleportLocation Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Location != nullptr)
		*Location = std::move(Parms.Location);
}

}

