#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: ORS

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"
#include "Engine_classes.hpp"
#include "FortniteGame_classes.hpp"
#include "ORS_structs.hpp"


namespace SDK
{

// Class ORS.ORSIsReplicated
// 0x0000 (0x0000 - 0x0000)
class IORSIsReplicated final
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"ORSIsReplicated">();
	}
	static class IORSIsReplicated* GetDefaultObj()
	{
		return GetDefaultObjImpl<IORSIsReplicated>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};

// Class ORS.ORSNetSerializable
// 0x0000 (0x0000 - 0x0000)
class IORSNetSerializable final
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"ORSNetSerializable">();
	}
	static class IORSNetSerializable* GetDefaultObj()
	{
		return GetDefaultObjImpl<IORSNetSerializable>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};

// Class ORS.ORSNotify
// 0x0000 (0x0000 - 0x0000)
class IORSNotify final
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"ORSNotify">();
	}
	static class IORSNotify* GetDefaultObj()
	{
		return GetDefaultObjImpl<IORSNotify>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};

// Class ORS.ORSSetNetAddressable
// 0x0000 (0x0000 - 0x0000)
class IORSSetNetAddressable final
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"ORSSetNetAddressable">();
	}
	static class IORSSetNetAddressable* GetDefaultObj()
	{
		return GetDefaultObjImpl<IORSSetNetAddressable>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};

// Class ORS.ORSSystemNotify
// 0x0000 (0x0000 - 0x0000)
class IORSSystemNotify final
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"ORSSystemNotify">();
	}
	static class IORSSystemNotify* GetDefaultObj()
	{
		return GetDefaultObjImpl<IORSSystemNotify>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};

// Class ORS.ORSActor
// 0x0028 (0x02B8 - 0x0290)
class AORSActor : public AActor
{
public:
	uint8                                         Pad_290[0x20];                                     // 0x0290(0x0020)(Fixing Size After Last Property [ Dumper-8 ])
	class UORSGroupComponent*                     GroupComponent;                                    // 0x02B0(0x0008)(Edit, BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, NoDestructor, Protected, PersistentInstance, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"ORSActor">();
	}
	static class AORSActor* GetDefaultObj()
	{
		return GetDefaultObjImpl<AORSActor>();
	}
};

// Class ORS.ORSActorComponent
// 0x0028 (0x00C8 - 0x00A0)
class UORSActorComponent final : public UActorComponent
{
public:
	uint8                                         Pad_A0[0x28];                                      // 0x00A0(0x0028)(Fixing Struct Size After Last Property [ Dumper-8 ])

public:
	void OnOwnerAdded(const class AActor* Actor);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"ORSActorComponent">();
	}
	static class UORSActorComponent* GetDefaultObj()
	{
		return GetDefaultObjImpl<UORSActorComponent>();
	}
};

// Class ORS.ORSCheatManager
// 0x0000 (0x0028 - 0x0028)
class UORSCheatManager final : public UChildCheatManager
{
public:
	void ORSDebug(const class FName& Path);
	void ORSListObjects();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"ORSCheatManager">();
	}
	static class UORSCheatManager* GetDefaultObj()
	{
		return GetDefaultObjImpl<UORSCheatManager>();
	}
};

// Class ORS.ORSClassTuple
// 0x0060 (0x0088 - 0x0028)
class UORSClassTuple final : public UObject
{
public:
	struct FClassTuple                            Tuple;                                             // 0x0028(0x0040)(NoDestructor, NativeAccessSpecifierPublic)
	uint8                                         Pad_68[0x20];                                      // 0x0068(0x0020)(Fixing Struct Size After Last Property [ Dumper-8 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"ORSClassTuple">();
	}
	static class UORSClassTuple* GetDefaultObj()
	{
		return GetDefaultObjImpl<UORSClassTuple>();
	}
};

// Class ORS.ORSClassTupleCollection
// 0x0060 (0x0088 - 0x0028)
class UORSClassTupleCollection final : public UObject
{
public:
	TArray<class UORSClassTuple*>                 ClassTuples;                                       // 0x0028(0x0010)(ZeroConstructor, UObjectWrapper, NativeAccessSpecifierPublic)
	TMap<TSubclassOf<class UObject>, struct FORSClassTupleList> ClassMap;                            // 0x0038(0x0050)(NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"ORSClassTupleCollection">();
	}
	static class UORSClassTupleCollection* GetDefaultObj()
	{
		return GetDefaultObjImpl<UORSClassTupleCollection>();
	}
};

// Class ORS.ORSConfig
// 0x0080 (0x00A8 - 0x0028)
class UORSConfig final : public UObject
{
public:
	TArray<class FName>                           HighPriority;                                      // 0x0028(0x0010)(ZeroConstructor, Config, NativeAccessSpecifierPublic)
	TArray<class FName>                           LowPriority;                                       // 0x0038(0x0010)(ZeroConstructor, Config, NativeAccessSpecifierPublic)
	TArray<class FName>                           Optional;                                          // 0x0048(0x0010)(ZeroConstructor, Config, NativeAccessSpecifierPublic)
	uint8                                         Pad_58[0x50];                                      // 0x0058(0x0050)(Fixing Struct Size After Last Property [ Dumper-8 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"ORSConfig">();
	}
	static class UORSConfig* GetDefaultObj()
	{
		return GetDefaultObjImpl<UORSConfig>();
	}
};

// Class ORS.ORSGlobal
// 0x0010 (0x0038 - 0x0028)
class UORSGlobal final : public UObject
{
public:
	TArray<class UORSInstance*>                   Instances;                                         // 0x0028(0x0010)(ZeroConstructor, UObjectWrapper, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"ORSGlobal">();
	}
	static class UORSGlobal* GetDefaultObj()
	{
		return GetDefaultObjImpl<UORSGlobal>();
	}
};

// Class ORS.ORSGroup
// 0x0138 (0x0160 - 0x0028)
class UORSGroup final : public UObject
{
public:
	class UObject*                                Owner;                                             // 0x0028(0x0008)(ZeroConstructor, Transient, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UORSGroupComponent*                     GroupComponent;                                    // 0x0030(0x0008)(ExportObject, ZeroConstructor, Transient, InstancedReference, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_38[0x20];                                      // 0x0038(0x0020)(Fixing Size After Last Property [ Dumper-8 ])
	class UORSGroup*                              Parent;                                            // 0x0058(0x0008)(ZeroConstructor, Transient, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<class UORSGroup*>                      Children;                                          // 0x0060(0x0010)(ZeroConstructor, Transient, UObjectWrapper, NativeAccessSpecifierPublic)
	uint8                                         Pad_70[0xF0];                                      // 0x0070(0x00F0)(Fixing Struct Size After Last Property [ Dumper-8 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"ORSGroup">();
	}
	static class UORSGroup* GetDefaultObj()
	{
		return GetDefaultObjImpl<UORSGroup>();
	}
};

// Class ORS.ORSGroupComponent
// 0x0080 (0x0120 - 0x00A0)
class UORSGroupComponent final : public UActorComponent
{
public:
	bool                                          bGlobal;                                           // 0x00A0(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_A1[0x7];                                       // 0x00A1(0x0007)(Fixing Size After Last Property [ Dumper-8 ])
	TArray<class UObject*>                        RegisteredObjects;                                 // 0x00A8(0x0010)(ZeroConstructor, Transient, Protected, UObjectWrapper, NativeAccessSpecifierProtected)
	TArray<class UObject*>                        ReplicatedObjectInstances;                         // 0x00B8(0x0010)(ZeroConstructor, Transient, Protected, UObjectWrapper, NativeAccessSpecifierProtected)
	TArray<class UObject*>                        ReplicatedObjectReferences;                        // 0x00C8(0x0010)(Net, ZeroConstructor, Transient, RepNotify, Protected, UObjectWrapper, NativeAccessSpecifierProtected)
	TArray<class UObject*>                        OldReplicatedObjectReferences;                     // 0x00D8(0x0010)(ZeroConstructor, Protected, UObjectWrapper, NativeAccessSpecifierProtected)
	TArray<struct FORSNetSerializableReplicationProxy> ReplicatedNetSerializeObjects;                // 0x00E8(0x0010)(Net, ZeroConstructor, Transient, RepNotify, Protected, NativeAccessSpecifierProtected)
	TArray<class UObject*>                        ReplayNetSerializeObjects;                         // 0x00F8(0x0010)(Net, ZeroConstructor, Transient, RepNotify, Protected, UObjectWrapper, NativeAccessSpecifierProtected)
	TArray<class UObject*>                        OldReplicatedNetSerializeObjects;                  // 0x0108(0x0010)(ZeroConstructor, Protected, UObjectWrapper, NativeAccessSpecifierProtected)
	uint8                                         Pad_118[0x8];                                      // 0x0118(0x0008)(Fixing Struct Size After Last Property [ Dumper-8 ])

public:
	void OnRep_ReplayNetSerializeObjects();
	void OnRep_ReplicatedNetSerializeObjects();
	void OnRep_ReplicatedObjectReferences();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"ORSGroupComponent">();
	}
	static class UORSGroupComponent* GetDefaultObj()
	{
		return GetDefaultObjImpl<UORSGroupComponent>();
	}
};

// Class ORS.ORSInstance
// 0x0158 (0x0180 - 0x0028)
class UORSInstance final : public UObject
{
public:
	class UGameInstance*                          GameInstance;                                      // 0x0028(0x0008)(ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UORSGroup*                              GlobalGroup;                                       // 0x0030(0x0008)(ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_38[0x50];                                      // 0x0038(0x0050)(Fixing Size After Last Property [ Dumper-8 ])
	class UORSClassTupleCollection*               ClassTuples;                                       // 0x0088(0x0008)(ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UORSSubscriptionCollection*             Subscriptions;                                     // 0x0090(0x0008)(ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_98[0xE8];                                      // 0x0098(0x00E8)(Fixing Struct Size After Last Property [ Dumper-8 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"ORSInstance">();
	}
	static class UORSInstance* GetDefaultObj()
	{
		return GetDefaultObjImpl<UORSInstance>();
	}
};

// Class ORS.ORSReplicatedObject
// 0x0018 (0x0040 - 0x0028)
class UORSReplicatedObject : public UObject
{
public:
	uint8                                         Pad_28[0x10];                                      // 0x0028(0x0010)(Fixing Size After Last Property [ Dumper-8 ])
	bool                                          bReplicated;                                       // 0x0038(0x0001)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_39[0x7];                                       // 0x0039(0x0007)(Fixing Struct Size After Last Property [ Dumper-8 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"ORSReplicatedObject">();
	}
	static class UORSReplicatedObject* GetDefaultObj()
	{
		return GetDefaultObjImpl<UORSReplicatedObject>();
	}
};

// Class ORS.ORSObject
// 0x0000 (0x0040 - 0x0040)
class UORSObject final : public UORSReplicatedObject
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"ORSObject">();
	}
	static class UORSObject* GetDefaultObj()
	{
		return GetDefaultObjImpl<UORSObject>();
	}
};

// Class ORS.ORSSubscriptionCollection
// 0x0038 (0x0060 - 0x0028)
class UORSSubscriptionCollection final : public UObject
{
public:
	uint8                                         Pad_28[0x38];                                      // 0x0028(0x0038)(Fixing Struct Size After Last Property [ Dumper-8 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"ORSSubscriptionCollection">();
	}
	static class UORSSubscriptionCollection* GetDefaultObj()
	{
		return GetDefaultObjImpl<UORSSubscriptionCollection>();
	}
};

// Class ORS.ORSSubsystemShutdown
// 0x0000 (0x0028 - 0x0028)
class UORSSubsystemShutdown final : public UObject
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"ORSSubsystemShutdown">();
	}
	static class UORSSubsystemShutdown* GetDefaultObj()
	{
		return GetDefaultObjImpl<UORSSubsystemShutdown>();
	}
};

// Class ORS.ORSSubsystem
// 0x0058 (0x0088 - 0x0030)
class UORSSubsystem final : public UGameInstanceSubsystem
{
public:
	struct FORSInstanceRef                        ORSInstance;                                       // 0x0030(0x0010)(NoDestructor, NativeAccessSpecifierPublic)
	uint8                                         Pad_40[0x20];                                      // 0x0040(0x0020)(Fixing Size After Last Property [ Dumper-8 ])
	class UWorld*                                 GameWorld;                                         // 0x0060(0x0008)(ZeroConstructor, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class AORSWorldActor*                         WorldActor;                                        // 0x0068(0x0008)(ZeroConstructor, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class UGameFrameworkComponentManager*         ComponentManager;                                  // 0x0070(0x0008)(ZeroConstructor, Transient, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_78[0x10];                                      // 0x0078(0x0010)(Fixing Struct Size After Last Property [ Dumper-8 ])

public:
	void OnActorDestroyed(class AActor* Actor);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"ORSSubsystem">();
	}
	static class UORSSubsystem* GetDefaultObj()
	{
		return GetDefaultObjImpl<UORSSubsystem>();
	}
};

// Class ORS.ORSSystemActor
// 0x0030 (0x02C0 - 0x0290)
class AORSSystemActor : public AActor
{
public:
	uint8                                         Pad_290[0x20];                                     // 0x0290(0x0020)(Fixing Size After Last Property [ Dumper-8 ])
	struct FORSGroupObjectList                    SystemObjects;                                     // 0x02B0(0x0010)(Protected, NativeAccessSpecifierProtected)

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"ORSSystemActor">();
	}
	static class AORSSystemActor* GetDefaultObj()
	{
		return GetDefaultObjImpl<AORSSystemActor>();
	}
};

// Class ORS.ORSPlaceableSystemActor
// 0x0000 (0x02C0 - 0x02C0)
class AORSPlaceableSystemActor final : public AORSSystemActor
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"ORSPlaceableSystemActor">();
	}
	static class AORSPlaceableSystemActor* GetDefaultObj()
	{
		return GetDefaultObjImpl<AORSPlaceableSystemActor>();
	}
};

// Class ORS.ORSActorsInitialized
// 0x0000 (0x0028 - 0x0028)
class UORSActorsInitialized final : public UObject
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"ORSActorsInitialized">();
	}
	static class UORSActorsInitialized* GetDefaultObj()
	{
		return GetDefaultObjImpl<UORSActorsInitialized>();
	}
};

// Class ORS.ORSWorldActor
// 0x0000 (0x02B8 - 0x02B8)
class AORSWorldActor final : public AORSActor
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"ORSWorldActor">();
	}
	static class AORSWorldActor* GetDefaultObj()
	{
		return GetDefaultObjImpl<AORSWorldActor>();
	}
};

}

