#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: ORS

#include "Basic.hpp"

#include "ORS_classes.hpp"
#include "ORS_parameters.hpp"


namespace SDK
{

// Function ORS.ORSActorComponent.OnOwnerAdded
// (Final, Native, Private)
// Parameters:
// const class AActor*                     Actor                                                  (ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UORSActorComponent::OnOwnerAdded(const class AActor* Actor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ORSActorComponent", "OnOwnerAdded");

	Params::ORSActorComponent_OnOwnerAdded Parms{};

	Parms.Actor = Actor;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function ORS.ORSCheatManager.ORSDebug
// (Final, Exec, Native, Protected, HasOutParams)
// Parameters:
// const class FName&                      Path                                                   (ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UORSCheatManager::ORSDebug(const class FName& Path)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ORSCheatManager", "ORSDebug");

	Params::ORSCheatManager_ORSDebug Parms{};

	Parms.Path = Path;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function ORS.ORSCheatManager.ORSListObjects
// (Final, Exec, Native, Protected)

void UORSCheatManager::ORSListObjects()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ORSCheatManager", "ORSListObjects");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function ORS.ORSGroupComponent.OnRep_ReplayNetSerializeObjects
// (Final, Native, Protected)

void UORSGroupComponent::OnRep_ReplayNetSerializeObjects()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ORSGroupComponent", "OnRep_ReplayNetSerializeObjects");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function ORS.ORSGroupComponent.OnRep_ReplicatedNetSerializeObjects
// (Final, Native, Protected)

void UORSGroupComponent::OnRep_ReplicatedNetSerializeObjects()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ORSGroupComponent", "OnRep_ReplicatedNetSerializeObjects");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function ORS.ORSGroupComponent.OnRep_ReplicatedObjectReferences
// (Final, Native, Protected)

void UORSGroupComponent::OnRep_ReplicatedObjectReferences()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ORSGroupComponent", "OnRep_ReplicatedObjectReferences");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function ORS.ORSSubsystem.OnActorDestroyed
// (Final, Native, Protected)
// Parameters:
// class AActor*                           Actor                                                  (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UORSSubsystem::OnActorDestroyed(class AActor* Actor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ORSSubsystem", "OnActorDestroyed");

	Params::ORSSubsystem_OnActorDestroyed Parms{};

	Parms.Actor = Actor;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}

}

