#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: PBWA_M1_ArchwayLarge

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PBWA_M1_ArchwayLarge.PBWA_M1_ArchwayLarge_C
// 0x0000 (0x0D50 - 0x0D50)
class APBWA_M1_ArchwayLarge_C final : public ABuildingWall
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"PBWA_M1_ArchwayLarge_C">();
	}
	static class APBWA_M1_ArchwayLarge_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<APBWA_M1_ArchwayLarge_C>();
	}
};

}

