#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: QRCodeGenerator

#include "Basic.hpp"

#include "Engine_classes.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// Class QRCodeGenerator.QRCodeGeneratorBlueprintFunctionLibrary
// 0x0000 (0x0028 - 0x0028)
class UQRCodeGeneratorBlueprintFunctionLibrary final : public UBlueprintFunctionLibrary
{
public:
	static class UTexture2D* GenerateQRCodeTextureFromString(const class FString& StringToEncode);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"QRCodeGeneratorBlueprintFunctionLibrary">();
	}
	static class UQRCodeGeneratorBlueprintFunctionLibrary* GetDefaultObj()
	{
		return GetDefaultObjImpl<UQRCodeGeneratorBlueprintFunctionLibrary>();
	}
};

// Class QRCodeGenerator.QRCodeGeneratorUserWidget
// 0x0018 (0x02D0 - 0x02B8)
class UQRCodeGeneratorUserWidget final : public UUserWidget
{
public:
	class UTexture2D*                             QRCodeTexture2D;                                   // 0x02B8(0x0008)(BlueprintVisible, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void()>              OnQRCodeTextureUpdated;                            // 0x02C0(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)

public:
	void EncodeString(const class FString& StringToEncode);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"QRCodeGeneratorUserWidget">();
	}
	static class UQRCodeGeneratorUserWidget* GetDefaultObj()
	{
		return GetDefaultObjImpl<UQRCodeGeneratorUserWidget>();
	}
};

}

