#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: QuestMapInactiveCategoryButton

#include "Basic.hpp"

#include "QuestMapInactiveCategoryButton_classes.hpp"
#include "QuestMapInactiveCategoryButton_parameters.hpp"


namespace SDK
{

// Function QuestMapInactiveCategoryButton.QuestMapInactiveCategoryButton_C.ShowNewBang
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bEnabled                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UQuestMapInactiveCategoryButton_C::ShowNewBang(bool bEnabled)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("QuestMapInactiveCategoryButton_C", "ShowNewBang");

	Params::QuestMapInactiveCategoryButton_C_ShowNewBang Parms{};

	Parms.bEnabled = bEnabled;

	UObject::ProcessEvent(Func, &Parms);
}


// Function QuestMapInactiveCategoryButton.QuestMapInactiveCategoryButton_C.ExecuteUbergraph_QuestMapInactiveCategoryButton
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UQuestMapInactiveCategoryButton_C::ExecuteUbergraph_QuestMapInactiveCategoryButton(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("QuestMapInactiveCategoryButton_C", "ExecuteUbergraph_QuestMapInactiveCategoryButton");

	Params::QuestMapInactiveCategoryButton_C_ExecuteUbergraph_QuestMapInactiveCategoryButton Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function QuestMapInactiveCategoryButton.QuestMapInactiveCategoryButton_C.BP_Populate
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// const class FText&                      Title                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UQuestMapInactiveCategoryButton_C::BP_Populate(const class FText& Title)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("QuestMapInactiveCategoryButton_C", "BP_Populate");

	Params::QuestMapInactiveCategoryButton_C_BP_Populate Parms{};

	Parms.Title = std::move(Title);

	UObject::ProcessEvent(Func, &Parms);
}


// Function QuestMapInactiveCategoryButton.QuestMapInactiveCategoryButton_C.BP_OnSelected
// (Event, Protected, BlueprintEvent)

void UQuestMapInactiveCategoryButton_C::BP_OnSelected()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("QuestMapInactiveCategoryButton_C", "BP_OnSelected");

	UObject::ProcessEvent(Func, nullptr);
}


// Function QuestMapInactiveCategoryButton.QuestMapInactiveCategoryButton_C.BP_OnDeselected
// (Event, Protected, BlueprintEvent)

void UQuestMapInactiveCategoryButton_C::BP_OnDeselected()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("QuestMapInactiveCategoryButton_C", "BP_OnDeselected");

	UObject::ProcessEvent(Func, nullptr);
}

}

