#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: SportbikeRuntime

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "MotorcycleRuntime_classes.hpp"


namespace SDK
{

// Class SportbikeRuntime.FortSportbikeAnimInstance
// 0x0020 (0x06B0 - 0x0690)
class UFortSportbikeAnimInstance final : public UFortMotorcycleVehicleAnimInstance
{
public:
	struct FRotator                               LimitedWheelRotationFR;                            // 0x0688(0x0018)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
	bool                                          HasPassenger;                                      // 0x06A0(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ShouldPlayGroundTrick;                             // 0x06A1(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          IsWheelie;                                         // 0x06A2(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          StateRuleFromWheelieToGroundTrickOutro;            // 0x06A3(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          SportBikeWheelieEarlyOut;                          // 0x06A4(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ShouldExitFromLocomotion;                          // 0x06A5(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          IsChangingGear;                                    // 0x06A6(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_6A7[0x9];                                      // 0x06A7(0x0009)(Fixing Struct Size After Last Property [ Dumper-8 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"FortSportbikeAnimInstance">();
	}
	static class UFortSportbikeAnimInstance* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFortSportbikeAnimInstance>();
	}
};

// Class SportbikeRuntime.FortSportbikeDriverAnimInstance
// 0x0030 (0x0970 - 0x0940)
class UFortSportbikeDriverAnimInstance final : public UFortPlayerAnimInstance_MotorcycleDriver
{
public:
	bool                                          SportBikeWheelieEarlyOut;                          // 0x0940(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          StateRuleFromWheelieToGroundTrickOutro;            // 0x0941(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          EarlyExitFromGroundTrick;                          // 0x0942(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          IsBoostingWithNoPassenger;                         // 0x0943(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         MotorcycleGear;                                    // 0x0944(0x0004)(BlueprintVisible, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         CurrentGear;                                       // 0x0948(0x0004)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         PreviousGear;                                      // 0x094C(0x0004)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          IsChangingGear;                                    // 0x0950(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_951[0x3];                                      // 0x0951(0x0003)(Fixing Size After Last Property [ Dumper-8 ])
	float                                         SuperSlideBlendAlpha;                              // 0x0954(0x0004)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         SuperSlideBlendStart;                              // 0x0958(0x0004)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         SuperSlideBlendEnd;                                // 0x095C(0x0004)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          IsSuperSliding;                                    // 0x0960(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_961[0xF];                                      // 0x0961(0x000F)(Fixing Struct Size After Last Property [ Dumper-8 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"FortSportbikeDriverAnimInstance">();
	}
	static class UFortSportbikeDriverAnimInstance* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFortSportbikeDriverAnimInstance>();
	}
};

// Class SportbikeRuntime.FortSportbikeVehicle
// 0x0010 (0x2590 - 0x2580)
class AFortSportbikeVehicle final : public AFortMotorcycleVehicle
{
public:
	uint8                                         Pad_2580[0x10];                                    // 0x2580(0x0010)(Fixing Struct Size After Last Property [ Dumper-8 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"FortSportbikeVehicle">();
	}
	static class AFortSportbikeVehicle* GetDefaultObj()
	{
		return GetDefaultObjImpl<AFortSportbikeVehicle>();
	}
};

// Class SportbikeRuntime.FortSportbikeVehicleConfigs
// 0x0000 (0x0C50 - 0x0C50)
class UFortSportbikeVehicleConfigs final : public UFortMotorcycleVehicleConfigs
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"FortSportbikeVehicleConfigs">();
	}
	static class UFortSportbikeVehicleConfigs* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFortSportbikeVehicleConfigs>();
	}
};

}

