#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: StyleSheets

#include "Basic.hpp"

#include "StyleSheets_classes.hpp"
#include "StyleSheets_parameters.hpp"


namespace SDK
{

// Function StyleSheets.StylableWidget.BP_OnWidgetStyled
// (RequiredAPI, Event, Protected, BlueprintEvent)

void IStylableWidget::BP_OnWidgetStyled()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("StylableWidget", "BP_OnWidgetStyled");

	AsUObject()->ProcessEvent(Func, nullptr);
}


// Function StyleSheets.StyleSheetsSubsystem.UpdateWidgetStyleTags
// (Final, RequiredAPI, Native, Static, Public, BlueprintCallable)
// Parameters:
// class UWidget*                          InWidget                                               (Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const TArray<struct FGameplayTag>&      InAddedTags                                            (Parm, ZeroConstructor, NativeAccessSpecifierPublic)
// const TArray<struct FGameplayTag>&      InRemovedTags                                          (Parm, ZeroConstructor, NativeAccessSpecifierPublic)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UStyleSheetsSubsystem::UpdateWidgetStyleTags(class UWidget* InWidget, const TArray<struct FGameplayTag>& InAddedTags, const TArray<struct FGameplayTag>& InRemovedTags)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("StyleSheetsSubsystem", "UpdateWidgetStyleTags");

	Params::StyleSheetsSubsystem_UpdateWidgetStyleTags Parms{};

	Parms.InWidget = InWidget;
	Parms.InAddedTags = std::move(InAddedTags);
	Parms.InRemovedTags = std::move(InRemovedTags);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}

}

