#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: SunRoseZeusGameplayRuntime

#include "Basic.hpp"

#include "GameplayTags_structs.hpp"
#include "FortniteGame_classes.hpp"
#include "TargetingSystem_structs.hpp"
#include "GameplayAbilities_structs.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// Class SunRoseZeusGameplayRuntime.SunRose_Zeus_Player_LayerAnimInstance
// 0x0000 (0x13D0 - 0x13D0)
class USunRose_Zeus_Player_LayerAnimInstance final : public UFortPlayerAnimInstanceProxy
{
public:
	bool                                          bIsThrowActive;                                    // 0x13C8(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_13C9[0x3];                                     // 0x13C9(0x0003)(Fixing Size After Last Property [ Dumper-8 ])
	struct FGameplayTag                           LightningAbilityActiveTag;                         // 0x13CC(0x0004)(Edit, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"SunRose_Zeus_Player_LayerAnimInstance">();
	}
	static class USunRose_Zeus_Player_LayerAnimInstance* GetDefaultObj()
	{
		return GetDefaultObjImpl<USunRose_Zeus_Player_LayerAnimInstance>();
	}
};

// Class SunRoseZeusGameplayRuntime.SunRose_Zeus_Weapon_Hand_AnimInstance
// 0x0010 (0x0480 - 0x0470)
class USunRose_Zeus_Weapon_Hand_AnimInstance final : public UFortWeaponAnimInstance
{
public:
	bool                                          bIsThrow;                                          // 0x0468(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_469[0x7];                                      // 0x0469(0x0007)(Fixing Size After Last Property [ Dumper-8 ])
	class FString                                 LightningThrowMontageName;                         // 0x0470(0x0010)(Edit, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"SunRose_Zeus_Weapon_Hand_AnimInstance">();
	}
	static class USunRose_Zeus_Weapon_Hand_AnimInstance* GetDefaultObj()
	{
		return GetDefaultObjImpl<USunRose_Zeus_Weapon_Hand_AnimInstance>();
	}
};

// Class SunRoseZeusGameplayRuntime.BuildingGameplayActorZeusThunderstorm
// 0x0070 (0x09F0 - 0x0980)
class alignas(0x10) ABuildingGameplayActorZeusThunderstorm final : public ABuildingGameplayActor
{
public:
	struct FScalableFloat                         Row_TelegraphDuration;                             // 0x0980(0x0028)(Edit, DisableEditOnInstance, Protected, NativeAccessSpecifierProtected)
	struct FScalableFloat                         Row_LightningStrikeFXDelay;                        // 0x09A8(0x0028)(Edit, DisableEditOnInstance, Protected, NativeAccessSpecifierProtected)
	uint8                                         Pad_9D0[0x20];                                     // 0x09D0(0x0020)(Fixing Struct Size After Last Property [ Dumper-8 ])

public:
	struct FVector GetStrikeTargetingLocation(const struct FTargetingRequestHandle& TargetingHandle);
	void K2_OnLightningStrike(const struct FVector& Location);
	void K2_OnLightningStrikeFX(const struct FVector& Location, const float BoltHeight);
	void K2_OnTelegraphEnd();
	void K2_OnTelegraphStart(const struct FVector& Location);
	void OnTelegraphEnd();
	void OnTelegraphStart(const struct FVector& Location);
	void SetStrikeTargetingLocation(const struct FTargetingRequestHandle& TargetingHandle, const struct FVector& Location);
	void StartLightningFX();
	void StartLightningStrike(const struct FVector& Location, const float BoltHeight);
	void StrikeLightning(const struct FVector& Location);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"BuildingGameplayActorZeusThunderstorm">();
	}
	static class ABuildingGameplayActorZeusThunderstorm* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABuildingGameplayActorZeusThunderstorm>();
	}
};

// Class SunRoseZeusGameplayRuntime.FortProjectileSunRoseLightning
// 0x0310 (0x0DC8 - 0x0AB8)
class AFortProjectileSunRoseLightning : public AFortProjectileBase
{
public:
	TArray<TSubclassOf<class UGameplayEffect>>    ExplosionDamageGEs;                                // 0x0AB8(0x0010)(Edit, ZeroConstructor, DisableEditOnInstance, Protected, UObjectWrapper, NativeAccessSpecifierProtected)
	float                                         ExplosionGELevel;                                  // 0x0AC8(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	ECollisionChannel                             ExplosionTraceChannel;                             // 0x0ACC(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_ACD[0x3];                                      // 0x0ACD(0x0003)(Fixing Size After Last Property [ Dumper-8 ])
	struct FScalableFloat                         MaxHitsPerFrame;                                   // 0x0AD0(0x0028)(Edit, Protected, NativeAccessSpecifierProtected)
	uint8                                         Pad_AF8[0x2C8];                                    // 0x0AF8(0x02C8)(Fixing Size After Last Property [ Dumper-8 ])
	struct FTargetingRequestHandle                ExplosionAsyncLOSTargetingHandle;                  // 0x0DC0(0x0004)(Transient, NoDestructor, Protected, NativeAccessSpecifierProtected)
	uint8                                         Pad_DC4[0x4];                                      // 0x0DC4(0x0004)(Fixing Struct Size After Last Property [ Dumper-8 ])

public:
	void DoExplosionAsyncLOS();
	void OnExplosionFinished();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"FortProjectileSunRoseLightning">();
	}
	static class AFortProjectileSunRoseLightning* GetDefaultObj()
	{
		return GetDefaultObjImpl<AFortProjectileSunRoseLightning>();
	}
};

}

