#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: TextStyle_Header_S

#include "Basic.hpp"

#include "TextStyle_HeaderParent_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass TextStyle-Header-S.TextStyle-Header-S_C
// 0x0000 (0x01A0 - 0x01A0)
class UTextStyle_Header_S_C final : public UTextStyle_HeaderParent_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"TextStyle-Header-S_C">();
	}
	static class UTextStyle_Header_S_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTextStyle_Header_S_C>();
	}
};

}

