#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: VerseUI

#include "Basic.hpp"

#include "NetCore_structs.hpp"


namespace SDK
{

// ScriptStruct VerseUI.VerseUIUserWidgetViewmodel
// 0x001C (0x0028 - 0x000C)
struct FVerseUIUserWidgetViewmodel final : public FFastArraySerializerItem
{
public:
	class FName                                   Name;                                              // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UObject*                                Instance;                                          // 0x0010(0x0008)(ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UObject*                                AuthorityInstance;                                 // 0x0018(0x0008)(ZeroConstructor, Transient, RepSkip, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_20[0x8];                                       // 0x0020(0x0008)(Fixing Struct Size After Last Property [ Dumper-8 ])
};

// ScriptStruct VerseUI.VerseUIUserWidgetViewmodelList
// 0x0018 (0x0120 - 0x0108)
struct FVerseUIUserWidgetViewmodelList final : public FFastArraySerializer
{
public:
	TArray<struct FVerseUIUserWidgetViewmodel>    Viewmodels;                                        // 0x0108(0x0010)(ZeroConstructor, NativeAccessSpecifierPublic)
	class UVerseUIUserWidget*                     Owner;                                             // 0x0118(0x0008)(ZeroConstructor, Transient, RepSkip, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
};

// ScriptStruct VerseUI.VerseUIViewmodelRegistryTag
// 0x0038 (0x0038 - 0x0000)
struct FVerseUIViewmodelRegistryTag final
{
public:
	class FString                                 ViewmodelName;                                     // 0x0000(0x0010)(ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 ClassName;                                         // 0x0010(0x0010)(ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 ClassPackageName;                                  // 0x0020(0x0010)(ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bGeneratedClass;                                   // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bOptional;                                         // 0x0031(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_32[0x6];                                       // 0x0032(0x0006)(Fixing Struct Size After Last Property [ Dumper-8 ])
};

}

