#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: VerseSimulationMetadata_0

#include "Basic.hpp"

#include "VerseSimulationMetadata_0_structs.hpp"
#include "VerseNative_structs.hpp"


namespace SDK::Params
{

// Function VerseSimulationMetadata.Simulation.$InitCDO
// 0x0350 (0x0350 - 0x0000)
struct Simulation__InitCDO final
{
public:
	class UVerse_message*                         _ExprResultStack_0;                                // 0x0000(0x0008)(ExportObject, ZeroConstructor, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	FVerseFunctionProperty_                       _Callee_1;                                         // 0x0008(0x0010)(HasGetValueTypeHash)
	struct VerseSimulationMetadata_0::Ftuple_L_Kchar_M_Kchar_M_5b_Kchar_5dlocalizable__value_R _ExprResult_2; // 0x0018(0x0070)(HasGetValueTypeHash)
	FVerseStringProperty_                         _ExprResult_3;                                     // 0x0088(0x0010)(HasGetValueTypeHash)
	FVerseStringProperty_                         _ExprResult_4;                                     // 0x0098(0x0010)(HasGetValueTypeHash)
	TMap<FVerseStringProperty_, class UVerse_localizable_value*> _ExprResult_5;                      // 0x00A8(0x0050)(ContainsInstancedReference)
	TMap<EVerseFalse, EVerseFalse>                __verse_0xC87067A2_Map_1;                          // 0x00F8(0x0050)(ContainsInstancedReference)
	TMap<FVerseStringProperty_, class UVerse_localizable_value*> _ForResult_6;                       // 0x0148(0x0050)(ContainsInstancedReference)
	int64                                         _ForIndex_7;                                       // 0x0198(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EVerseFalse                                   __verse_0x589418B4_Key_3;                          // 0x01A0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EVerseFalse                                   __verse_0x31A8F10C_Value_3;                        // 0x01A1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         _ExprResult_8 : 1;                                 // 0x01A2(0x0001)(BitIndex: 0x00, PropSize: 0x0001 (NoDestructor, HasGetValueTypeHash))
	uint8                                         BitPad_1A2_1 : 7;                                  // 0x01A2(0x0001)(Fixing Bit-Field Size For New Byte [ Dumper-8 ])
	uint8                                         _ExprResult_9 : 1;                                 // 0x01A3(0x0001)(BitIndex: 0x00, PropSize: 0x0001 (NoDestructor, HasGetValueTypeHash))
	uint8                                         Pad_1A4[0x4];                                      // 0x01A4(0x0004)(Fixing Size After Last Property [ Dumper-8 ])
	class UVerse_message*                         _ExprResultStack_10;                               // 0x01A8(0x0008)(ExportObject, ZeroConstructor, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	FVerseFunctionProperty_                       _Callee_11;                                        // 0x01B0(0x0010)(HasGetValueTypeHash)
	struct VerseSimulationMetadata_0::Ftuple_L_Kchar_M_Kchar_M_5b_Kchar_5dlocalizable__value_R _ExprResult_12; // 0x01C0(0x0070)(HasGetValueTypeHash)
	FVerseStringProperty_                         _ExprResult_13;                                    // 0x0230(0x0010)(HasGetValueTypeHash)
	FVerseStringProperty_                         _ExprResult_14;                                    // 0x0240(0x0010)(HasGetValueTypeHash)
	TMap<FVerseStringProperty_, class UVerse_localizable_value*> _ExprResult_15;                     // 0x0250(0x0050)(ContainsInstancedReference)
	TMap<EVerseFalse, EVerseFalse>                __verse_0xC87067A2_Map_6;                          // 0x02A0(0x0050)(ContainsInstancedReference)
	TMap<FVerseStringProperty_, class UVerse_localizable_value*> _ForResult_16;                      // 0x02F0(0x0050)(ContainsInstancedReference)
	int64                                         _ForIndex_17;                                      // 0x0340(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EVerseFalse                                   __verse_0x589418B4_Key_8;                          // 0x0348(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EVerseFalse                                   __verse_0x31A8F10C_Value_8;                        // 0x0349(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         _ExprResult_18 : 1;                                // 0x034A(0x0001)(BitIndex: 0x00, PropSize: 0x0001 (NoDestructor, HasGetValueTypeHash))
	uint8                                         BitPad_34A_1 : 7;                                  // 0x034A(0x0001)(Fixing Bit-Field Size For New Byte [ Dumper-8 ])
	uint8                                         _ExprResult_19 : 1;                                // 0x034B(0x0001)(BitIndex: 0x00, PropSize: 0x0001 (NoDestructor, HasGetValueTypeHash))
};

}

