#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: WBP_MPLocker_SortFilter_Modal

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CommonUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_MPLocker_SortFilter_Modal.WBP_MPLocker_SortFilter_Modal_C
// 0x0048 (0x0440 - 0x03F8)
class UWBP_MPLocker_SortFilter_Modal_C final : public UCommonActivatableWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x03F8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWBP_MPLocker_SortFilterOptions_Section_C* Option_Section;                                 // 0x0400(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, DisableEditOnInstance, InstancedReference, DuplicateTransient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UFortSortFilterVM*                      FortSortFilterVM;                                  // 0x0408(0x0008)(BlueprintVisible, ZeroConstructor, Transient, DuplicateTransient, RepSkip, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	class UWidgetAnimation*                       Intro;                                             // 0x0410(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWBP_MPLocker_SortFilter_Section_C*     Filter_Section;                                    // 0x0418(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_MPLocker_SortFilter_Section_C*     Sort_Section;                                      // 0x0420(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_UIKit_Dialog_Base_C*               WBP_UIKit_Dialog_Base;                             // 0x0428(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UFortSortItemVM*                        Saved_Active_Sort_Item;                            // 0x0430(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	class UFortFilterItemVM*                      Saved_Active_Filter_Item;                          // 0x0438(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, UObjectWrapper, HasGetValueTypeHash)

public:
	void SetFortSortFilterVM(class UFortSortFilterVM* ViewModel);
	void SaveCurrentFilters();
	void RestoreFiltersToSaved();
	void PreConstruct(bool IsDesignTime);
	void ExecuteUbergraph_WBP_MPLocker_SortFilter_Modal(int32 EntryPoint);
	void ButtonClicked(int32 ButtonIndex);
	void BP_OnDeactivated();
	void BP_OnActivated();
	void BndEvt__WBP_MPLocker_SortFilter_Modal_Sort_Section_K2Node_ComponentBoundEvent_1_OnItemClicked__DelegateSignature(class UFortSortFilterItemVM* Item_Filter_VM);
	void BndEvt__WBP_MPLocker_SortFilter_Modal_Filter_Section_K2Node_ComponentBoundEvent_0_OnItemClicked__DelegateSignature(class UFortSortFilterItemVM* Item_Filter_VM);

	class UWidget* BP_GetDesiredFocusTarget() const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_MPLocker_SortFilter_Modal_C">();
	}
	static class UWBP_MPLocker_SortFilter_Modal_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_MPLocker_SortFilter_Modal_C>();
	}
};

}

