#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: WBP_Discovery_BlankTiles_RoundedCorners

#include "Basic.hpp"


namespace SDK::Params
{

// Function WBP_Discovery_BlankTiles_RoundedCorners.WBP_Discovery_BlankTiles_RoundedCorners_C.SetMessageTextOverrides
// 0x0010 (0x0010 - 0x0000)
struct WBP_Discovery_BlankTiles_RoundedCorners_C_SetMessageTextOverrides final
{
public:
	class FText                                   InTitle;                                           // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm)
};

// Function WBP_Discovery_BlankTiles_RoundedCorners.WBP_Discovery_BlankTiles_RoundedCorners_C.SetEntryTileSize
// 0x0018 (0x0018 - 0x0000)
struct WBP_Discovery_BlankTiles_RoundedCorners_C_SetEntryTileSize final
{
public:
	double                                        CallFunc_BreakVector2D_X;                          // 0x0000(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector2D_Y;                          // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_SetEntryWidth_NewWidth_ImplicitCast;      // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_SetEntryHeight_NewHeight_ImplicitCast;    // 0x0014(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function WBP_Discovery_BlankTiles_RoundedCorners.WBP_Discovery_BlankTiles_RoundedCorners_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct WBP_Discovery_BlankTiles_RoundedCorners_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function WBP_Discovery_BlankTiles_RoundedCorners.WBP_Discovery_BlankTiles_RoundedCorners_C.ExecuteUbergraph_WBP_Discovery_BlankTiles_RoundedCorners
// 0x0028 (0x0028 - 0x0000)
struct WBP_Discovery_BlankTiles_RoundedCorners_C_ExecuteUbergraph_WBP_Discovery_BlankTiles_RoundedCorners final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-8 ])
	int32                                         Temp_int_Variable;                                 // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_C[0x4];                                        // 0x000C(0x0004)(Fixing Size After Last Property [ Dumper-8 ])
	class UWBP_Discovery_BlankTileEntry_C*        CallFunc_SpawnObject_ReturnValue;                  // 0x0010(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Subtract_IntInt_ReturnValue;              // 0x001C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Max_ReturnValue;                          // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_LessEqual_IntInt_ReturnValue;             // 0x0024(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

}

