#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: WeaponModsUI

#include "Basic.hpp"

#include "WeaponModsUI_classes.hpp"
#include "WeaponModsUI_parameters.hpp"


namespace SDK
{

// Function WeaponModsUI.AthenaEquippedItemInfoWeaponMods.HandleWeaponFullyEquipped
// (Final, Native, Private)
// Parameters:
// class AFortWeapon*                      NewWeapon                                              (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class AFortWeapon*                      PrevWeapon                                             (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UAthenaEquippedItemInfoWeaponMods::HandleWeaponFullyEquipped(class AFortWeapon* NewWeapon, class AFortWeapon* PrevWeapon)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaEquippedItemInfoWeaponMods", "HandleWeaponFullyEquipped");

	Params::AthenaEquippedItemInfoWeaponMods_HandleWeaponFullyEquipped Parms{};

	Parms.NewWeapon = NewWeapon;
	Parms.PrevWeapon = PrevWeapon;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function WeaponModsUI.AthenaEquippedItemInfoWeaponMods.ResetItemInfo
// (Event, Protected, BlueprintEvent)

void UAthenaEquippedItemInfoWeaponMods::ResetItemInfo()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaEquippedItemInfoWeaponMods", "ResetItemInfo");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WeaponModsUI.AthenaEquippedItemInfoWeaponMods.SetItemSlotInfo
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// const struct FFortWeaponModSlot&        ModSlot                                                (ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic)

void UAthenaEquippedItemInfoWeaponMods::SetItemSlotInfo(const struct FFortWeaponModSlot& ModSlot)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaEquippedItemInfoWeaponMods", "SetItemSlotInfo");

	Params::AthenaEquippedItemInfoWeaponMods_SetItemSlotInfo Parms{};

	Parms.ModSlot = std::move(ModSlot);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WeaponModsUI.AthenaInventoryGroupWeaponMods.HandleButtonClicked
// (Final, Native, Protected, BlueprintCallable)
// Parameters:
// class UObject*                          Object                                                 (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UAthenaInventoryGroupWeaponMods::HandleButtonClicked(class UObject* Object)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaInventoryGroupWeaponMods", "HandleButtonClicked");

	Params::AthenaInventoryGroupWeaponMods_HandleButtonClicked Parms{};

	Parms.Object = Object;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function WeaponModsUI.AthenaInventoryGroupWeaponMods.CanWeaponEquipMod
// (Final, Native, Protected, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// const class AFortWeapon*                Weapon                                                 (ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const class UFortWeaponModItemDefinition*Mod                                                    (ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UAthenaInventoryGroupWeaponMods::CanWeaponEquipMod(const class AFortWeapon* Weapon, const class UFortWeaponModItemDefinition* Mod) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaInventoryGroupWeaponMods", "CanWeaponEquipMod");

	Params::AthenaInventoryGroupWeaponMods_CanWeaponEquipMod Parms{};

	Parms.Weapon = Weapon;
	Parms.Mod = Mod;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function WeaponModsUI.AthenaInventoryItemInfoWeaponMods.HandleInventoryItemSelected
// (Final, Native, Private)
// Parameters:
// class UFortItem*                        SelectedItem                                           (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UAthenaInventoryItemInfoWeaponMods::HandleInventoryItemSelected(class UFortItem* SelectedItem)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaInventoryItemInfoWeaponMods", "HandleInventoryItemSelected");

	Params::AthenaInventoryItemInfoWeaponMods_HandleInventoryItemSelected Parms{};

	Parms.SelectedItem = SelectedItem;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function WeaponModsUI.AthenaInventoryItemInfoWeaponMods.HandleInventoryPanelOpened
// (Final, Native, Private)

void UAthenaInventoryItemInfoWeaponMods::HandleInventoryPanelOpened()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaInventoryItemInfoWeaponMods", "HandleInventoryPanelOpened");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function WeaponModsUI.AthenaInventoryItemInfoWeaponMods.HandleWeaponModSlotsChanged
// (Final, Native, Private)
// Parameters:
// class AFortWeapon*                      Weapon                                                 (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UAthenaInventoryItemInfoWeaponMods::HandleWeaponModSlotsChanged(class AFortWeapon* Weapon)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaInventoryItemInfoWeaponMods", "HandleWeaponModSlotsChanged");

	Params::AthenaInventoryItemInfoWeaponMods_HandleWeaponModSlotsChanged Parms{};

	Parms.Weapon = Weapon;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function WeaponModsUI.AthenaInventoryItemInfoWeaponMods.ResetItemInfo
// (Event, Protected, BlueprintEvent)

void UAthenaInventoryItemInfoWeaponMods::ResetItemInfo()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaInventoryItemInfoWeaponMods", "ResetItemInfo");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WeaponModsUI.AthenaInventoryItemInfoWeaponMods.SetIsModifiableWeapon
// (Event, Protected, BlueprintEvent)
// Parameters:
// const bool                              bIsModifiable                                          (ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UAthenaInventoryItemInfoWeaponMods::SetIsModifiableWeapon(const bool bIsModifiable)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaInventoryItemInfoWeaponMods", "SetIsModifiableWeapon");

	Params::AthenaInventoryItemInfoWeaponMods_SetIsModifiableWeapon Parms{};

	Parms.bIsModifiable = bIsModifiable;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WeaponModsUI.AthenaInventoryItemInfoWeaponMods.SetItemSlotInfo
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// const struct FFortWeaponModSlot&        ModSlot                                                (ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic)

void UAthenaInventoryItemInfoWeaponMods::SetItemSlotInfo(const struct FFortWeaponModSlot& ModSlot)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaInventoryItemInfoWeaponMods", "SetItemSlotInfo");

	Params::AthenaInventoryItemInfoWeaponMods_SetItemSlotInfo Parms{};

	Parms.ModSlot = std::move(ModSlot);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WeaponModsUI.AthenaInventoryItemInfoWeaponMods.UpdateItemMods
// (Final, Native, Protected, BlueprintCallable)

void UAthenaInventoryItemInfoWeaponMods::UpdateItemMods()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaInventoryItemInfoWeaponMods", "UpdateItemMods");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function WeaponModsUI.AthenaInventoryItemInfoWeaponModsConfigurator.RemoveMod
// (Final, Native, Protected, BlueprintCallable)
// Parameters:
// class UFortWeaponModItemDefinition*     ModItemDef                                             (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UAthenaInventoryItemInfoWeaponModsConfigurator::RemoveMod(class UFortWeaponModItemDefinition* ModItemDef)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaInventoryItemInfoWeaponModsConfigurator", "RemoveMod");

	Params::AthenaInventoryItemInfoWeaponModsConfigurator_RemoveMod Parms{};

	Parms.ModItemDef = ModItemDef;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function WeaponModsUI.AthenaLastKillerWeaponModsInfo.SetKillerWeaponMods
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// const TArray<struct FFortWeaponModSlot>&ModSlots                                               (ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, NativeAccessSpecifierPublic)
// const bool                              bShouldShowMods                                        (ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UAthenaLastKillerWeaponModsInfo::SetKillerWeaponMods(const TArray<struct FFortWeaponModSlot>& ModSlots, const bool bShouldShowMods)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaLastKillerWeaponModsInfo", "SetKillerWeaponMods");

	Params::AthenaLastKillerWeaponModsInfo_SetKillerWeaponMods Parms{};

	Parms.ModSlots = std::move(ModSlots);
	Parms.bShouldShowMods = bShouldShowMods;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WeaponModsUI.AthenaMarkerDetailsExtensionWeaponMods.ResetModInfo
// (Event, Protected, BlueprintEvent)

void UAthenaMarkerDetailsExtensionWeaponMods::ResetModInfo()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaMarkerDetailsExtensionWeaponMods", "ResetModInfo");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WeaponModsUI.AthenaMarkerDetailsExtensionWeaponMods.SetModInfo
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// const struct FFortWeaponModSlot&        ModSlot                                                (ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic)

void UAthenaMarkerDetailsExtensionWeaponMods::SetModInfo(const struct FFortWeaponModSlot& ModSlot)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaMarkerDetailsExtensionWeaponMods", "SetModInfo");

	Params::AthenaMarkerDetailsExtensionWeaponMods_SetModInfo Parms{};

	Parms.ModSlot = std::move(ModSlot);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WeaponModsUI.AthenaPickupIndicatorWeaponMods.HandlePickupHovered
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// class AFortPickup*                      Pickup                                                 (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UAthenaPickupIndicatorWeaponMods::HandlePickupHovered(class AFortPickup* Pickup)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaPickupIndicatorWeaponMods", "HandlePickupHovered");

	Params::AthenaPickupIndicatorWeaponMods_HandlePickupHovered Parms{};

	Parms.Pickup = Pickup;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function WeaponModsUI.AthenaPickupIndicatorWeaponMods.HandleWeaponEquipped
// (Final, Native, Protected)
// Parameters:
// class AFortWeapon*                      NewWeapon                                              (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class AFortWeapon*                      PrevWeapon                                             (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UAthenaPickupIndicatorWeaponMods::HandleWeaponEquipped(class AFortWeapon* NewWeapon, class AFortWeapon* PrevWeapon)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaPickupIndicatorWeaponMods", "HandleWeaponEquipped");

	Params::AthenaPickupIndicatorWeaponMods_HandleWeaponEquipped Parms{};

	Parms.NewWeapon = NewWeapon;
	Parms.PrevWeapon = PrevWeapon;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function WeaponModsUI.AthenaPickupIndicatorWeaponMods.ResetItemInfo
// (Event, Protected, BlueprintEvent)

void UAthenaPickupIndicatorWeaponMods::ResetItemInfo()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaPickupIndicatorWeaponMods", "ResetItemInfo");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WeaponModsUI.AthenaPickupIndicatorWeaponMods.SetEquippedWeaponItemInfo
// (Event, Protected, BlueprintEvent)
// Parameters:
// const class UItemDefinitionBase*        ItemDef                                                (ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UAthenaPickupIndicatorWeaponMods::SetEquippedWeaponItemInfo(const class UItemDefinitionBase* ItemDef)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaPickupIndicatorWeaponMods", "SetEquippedWeaponItemInfo");

	Params::AthenaPickupIndicatorWeaponMods_SetEquippedWeaponItemInfo Parms{};

	Parms.ItemDef = ItemDef;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WeaponModsUI.AthenaPickupIndicatorWeaponMods.SetEquippedWeaponItemSlotInfo
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// const struct FFortWeaponModSlot&        ModSlot                                                (ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic)

void UAthenaPickupIndicatorWeaponMods::SetEquippedWeaponItemSlotInfo(const struct FFortWeaponModSlot& ModSlot)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaPickupIndicatorWeaponMods", "SetEquippedWeaponItemSlotInfo");

	Params::AthenaPickupIndicatorWeaponMods_SetEquippedWeaponItemSlotInfo Parms{};

	Parms.ModSlot = std::move(ModSlot);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WeaponModsUI.AthenaPickupIndicatorWeaponMods.SetItemModifiedWeaponName
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// const class FText&                      ModifiedWeaponName                                     (ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)

void UAthenaPickupIndicatorWeaponMods::SetItemModifiedWeaponName(const class FText& ModifiedWeaponName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaPickupIndicatorWeaponMods", "SetItemModifiedWeaponName");

	Params::AthenaPickupIndicatorWeaponMods_SetItemModifiedWeaponName Parms{};

	Parms.ModifiedWeaponName = std::move(ModifiedWeaponName);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WeaponModsUI.AthenaPickupIndicatorWeaponMods.SetItemSlotInfo
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// const struct FFortWeaponModSlot&        ModSlot                                                (ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic)

void UAthenaPickupIndicatorWeaponMods::SetItemSlotInfo(const struct FFortWeaponModSlot& ModSlot)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaPickupIndicatorWeaponMods", "SetItemSlotInfo");

	Params::AthenaPickupIndicatorWeaponMods_SetItemSlotInfo Parms{};

	Parms.ModSlot = std::move(ModSlot);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WeaponModsUI.AthenaPickupIndicatorWeaponMods.IsInspectViewCollapsedBySettings
// (Final, Native, Protected, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UAthenaPickupIndicatorWeaponMods::IsInspectViewCollapsedBySettings() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaPickupIndicatorWeaponMods", "IsInspectViewCollapsedBySettings");

	Params::AthenaPickupIndicatorWeaponMods_IsInspectViewCollapsedBySettings Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function WeaponModsUI.AthenaQuickBarSlotWeaponModsIndicator.HandleQuickBarSlotFocusChanged
// (Final, Native, Private)
// Parameters:
// EFortQuickBars                          QuickBarType                                           (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// int32                                   QuickBarSlot                                           (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UAthenaQuickBarSlotWeaponModsIndicator::HandleQuickBarSlotFocusChanged(EFortQuickBars QuickBarType, int32 QuickBarSlot)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaQuickBarSlotWeaponModsIndicator", "HandleQuickBarSlotFocusChanged");

	Params::AthenaQuickBarSlotWeaponModsIndicator_HandleQuickBarSlotFocusChanged Parms{};

	Parms.QuickBarType = QuickBarType;
	Parms.QuickBarSlot = QuickBarSlot;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function WeaponModsUI.AthenaQuickBarSlotWeaponModsIndicator.HandleWeaponFullyEquipped
// (Final, Native, Private)
// Parameters:
// class AFortWeapon*                      NewWeapon                                              (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class AFortWeapon*                      PrevWeapon                                             (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UAthenaQuickBarSlotWeaponModsIndicator::HandleWeaponFullyEquipped(class AFortWeapon* NewWeapon, class AFortWeapon* PrevWeapon)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaQuickBarSlotWeaponModsIndicator", "HandleWeaponFullyEquipped");

	Params::AthenaQuickBarSlotWeaponModsIndicator_HandleWeaponFullyEquipped Parms{};

	Parms.NewWeapon = NewWeapon;
	Parms.PrevWeapon = PrevWeapon;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function WeaponModsUI.AthenaQuickBarSlotWeaponModsIndicator.HandleWeaponModSlotsChanged
// (Final, Native, Private)
// Parameters:
// class AFortWeapon*                      Weapon                                                 (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UAthenaQuickBarSlotWeaponModsIndicator::HandleWeaponModSlotsChanged(class AFortWeapon* Weapon)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaQuickBarSlotWeaponModsIndicator", "HandleWeaponModSlotsChanged");

	Params::AthenaQuickBarSlotWeaponModsIndicator_HandleWeaponModSlotsChanged Parms{};

	Parms.Weapon = Weapon;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function WeaponModsUI.AthenaQuickBarSlotWeaponModsIndicator.ResetIconOpacities
// (Final, Native, Protected, BlueprintCallable)

void UAthenaQuickBarSlotWeaponModsIndicator::ResetIconOpacities()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaQuickBarSlotWeaponModsIndicator", "ResetIconOpacities");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function WeaponModsUI.AthenaQuickBarSlotWeaponModsIndicator.ResetItemInfo
// (Final, Native, Protected, BlueprintCallable)

void UAthenaQuickBarSlotWeaponModsIndicator::ResetItemInfo()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaQuickBarSlotWeaponModsIndicator", "ResetItemInfo");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function WeaponModsUI.AthenaQuickBarSlotWeaponModsIndicator.SetItemSlotInfo
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// const struct FFortWeaponModSlot&        ModSlot                                                (ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic)

void UAthenaQuickBarSlotWeaponModsIndicator::SetItemSlotInfo(const struct FFortWeaponModSlot& ModSlot)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaQuickBarSlotWeaponModsIndicator", "SetItemSlotInfo");

	Params::AthenaQuickBarSlotWeaponModsIndicator_SetItemSlotInfo Parms{};

	Parms.ModSlot = std::move(ModSlot);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WeaponModsUI.AthenaQuickBarSlotWeaponModsIndicator.SetItemSlotSelected
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bIsSelected                                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UAthenaQuickBarSlotWeaponModsIndicator::SetItemSlotSelected(bool bIsSelected)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaQuickBarSlotWeaponModsIndicator", "SetItemSlotSelected");

	Params::AthenaQuickBarSlotWeaponModsIndicator_SetItemSlotSelected Parms{};

	Parms.bIsSelected = bIsSelected;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WeaponModsUI.AthenaQuickBarSlotWeaponModsIndicator.SetItemSlotsInfo
// (Final, Native, Protected, HasOutParams, BlueprintCallable)
// Parameters:
// const TArray<struct FFortWeaponModSlot>&ModSlots                                               (ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, NativeAccessSpecifierPublic)

void UAthenaQuickBarSlotWeaponModsIndicator::SetItemSlotsInfo(const TArray<struct FFortWeaponModSlot>& ModSlots)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaQuickBarSlotWeaponModsIndicator", "SetItemSlotsInfo");

	Params::AthenaQuickBarSlotWeaponModsIndicator_SetItemSlotsInfo Parms{};

	Parms.ModSlots = std::move(ModSlots);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function WeaponModsUI.AthenaQuickBarSlotWeaponModsIndicator.UpdateModVisuals
// (Final, Native, Protected, HasOutParams, BlueprintCallable)
// Parameters:
// const TArray<struct FFortWeaponModSlot>&ModSlots                                               (ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, NativeAccessSpecifierPublic)

void UAthenaQuickBarSlotWeaponModsIndicator::UpdateModVisuals(const TArray<struct FFortWeaponModSlot>& ModSlots)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaQuickBarSlotWeaponModsIndicator", "UpdateModVisuals");

	Params::AthenaQuickBarSlotWeaponModsIndicator_UpdateModVisuals Parms{};

	Parms.ModSlots = std::move(ModSlots);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}

}

